#!/usr/bin/env bats
# Codex CLI generator smoke tests.
# Verifies our generators produce output shapes that match the Codex CLI
# upstream contract (codex-rs/config/src/hook_config.rs, docs/agents_md.md).
#
# Run with: bats tests/test_codex.bats

TOOLKIT_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"

setup_file() {
    export CX_DIR; CX_DIR="$(mktemp -d)"
    export CX_LOG_DIR; CX_LOG_DIR="$(mktemp -d)"
    python3 "$TOOLKIT_DIR/scripts/generate_codex.py" > "$CX_LOG_DIR/codex-md" 2>/dev/null
    echo $? > "$CX_LOG_DIR/codex-md.status"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_hooks.py" "$CX_DIR" > "$CX_LOG_DIR/codex-hooks.log" 2>/dev/null
    echo $? > "$CX_LOG_DIR/codex-hooks.status"
}

teardown_file() {
    rm -rf "$CX_DIR" "$CX_LOG_DIR"
}

@test "codex: native agent generator emits the required TOML schema" {
    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR"
    [ "$status" -eq 0 ]

    run python3 - "$TOOLKIT_DIR" "$CX_DIR" <<'PY'
import sys
import tomllib
from pathlib import Path

toolkit = Path(sys.argv[1])
target = Path(sys.argv[2]) / ".codex" / "agents"
sources = sorted((toolkit / "app" / "agents").glob("*.md"))
generated = sorted(target.glob("ai-toolkit-*.toml"))
assert len(generated) == len(sources), (len(generated), len(sources))

for source, output in zip(sources, generated, strict=True):
    data = tomllib.loads(output.read_text(encoding="utf-8"))
    assert set(data) == {"name", "description", "developer_instructions"}, data
    text = source.read_text(encoding="utf-8")
    frontmatter, body = text.split("---", 2)[1:]
    fields = {}
    for line in frontmatter.splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fields[key] = value.strip().strip('"').strip("'")
    assert data["name"] == fields["name"]
    assert data["description"] == fields["description"]
    assert data["developer_instructions"] == body.lstrip("\n").rstrip() + "\n"
    assert output.name == f"ai-toolkit-{data['name']}.toml"
PY
    [ "$status" -eq 0 ]
}

@test "codex: native agent sync preserves user files and cleans only managed stale files" {
    local agents_dir="$CX_DIR/.codex/agents"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR" >/dev/null

    cat > "$agents_dir/ai-toolkit-backend-specialist.toml" <<'TOML'
name = "user-backend"
description = "User-owned collision."
developer_instructions = "Keep this file unchanged."
TOML
    cp "$agents_dir/ai-toolkit-backend-specialist.toml" "$CX_LOG_DIR/user-collision.toml"
    printf '%s\n' 'name = "user-agent"' > "$agents_dir/user-agent.toml"
    printf '%s\n' 'name = "prefixed-user"' > "$agents_dir/ai-toolkit-prefixed-user.toml"
    cat > "$agents_dir/ai-toolkit-retired.toml" <<'TOML'
# Generated by ai-toolkit. Do not edit.
# ai-toolkit-managed: codex-agent
name = "retired"
description = "Stale managed fixture."
developer_instructions = "Remove this file."
TOML

    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR"
    [ "$status" -eq 0 ]
    cmp "$CX_LOG_DIR/user-collision.toml" "$agents_dir/ai-toolkit-backend-specialist.toml"
    [ -f "$agents_dir/user-agent.toml" ]
    [ -f "$agents_dir/ai-toolkit-prefixed-user.toml" ]
    [ ! -e "$agents_dir/ai-toolkit-retired.toml" ]
    grep -q '^# ai-toolkit-managed: codex-agent$' \
        "$agents_dir/ai-toolkit-code-reviewer.toml"

    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/agents.first"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR" >/dev/null
    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/agents.second"
    cmp "$CX_LOG_DIR/agents.first" "$CX_LOG_DIR/agents.second"
}

@test "codex: unmanaged logical name collision wins over managed toolkit agent" {
    local target_dir="$CX_DIR/logical-name-collision"
    local agents_dir="$target_dir/.codex/agents"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir" >/dev/null

    cat > "$agents_dir/custom.toml" <<'TOML'
name = "backend-specialist"
description = "User-owned backend agent."
developer_instructions = "Keep this file unchanged."
TOML
    printf '%s\n' 'name = "invalid-user-agent' > "$agents_dir/invalid-user.toml"
    cp "$agents_dir/custom.toml" "$CX_LOG_DIR/custom-agent.toml"
    cp "$agents_dir/invalid-user.toml" "$CX_LOG_DIR/invalid-user.toml"

    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir"
    [ "$status" -eq 0 ]
    [[ "$output" == *"Warning:"* ]]
    [[ "$output" == *"invalid-user.toml"* ]]
    cmp "$CX_LOG_DIR/custom-agent.toml" "$agents_dir/custom.toml"
    cmp "$CX_LOG_DIR/invalid-user.toml" "$agents_dir/invalid-user.toml"
    [ ! -e "$agents_dir/ai-toolkit-backend-specialist.toml" ]

    run python3 - "$agents_dir" <<'PY'
import sys
import tomllib
from pathlib import Path

matching = []
for path in Path(sys.argv[1]).glob("*.toml"):
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        continue
    if data.get("name") == "backend-specialist":
        matching.append(path.name)
assert matching == ["custom.toml"], matching
PY
    [ "$status" -eq 0 ]

    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/logical.first"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir" >/dev/null
    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/logical.second"
    cmp "$CX_LOG_DIR/logical.first" "$CX_LOG_DIR/logical.second"
}

@test "codex: native agent generator rejects symlinked output directories" {
    local codex_target="$CX_DIR/symlinked-codex"
    local codex_external="$CX_DIR/external-codex"
    mkdir -p "$codex_target" "$codex_external"
    printf '%s\n' 'keep codex sentinel' > "$codex_external/sentinel.txt"
    find "$codex_external" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/codex-external.before"
    ln -s "$codex_external" "$codex_target/.codex"

    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$codex_target"
    [ "$status" -ne 0 ]
    find "$codex_external" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/codex-external.after"
    cmp "$CX_LOG_DIR/codex-external.before" "$CX_LOG_DIR/codex-external.after"
    [ ! -e "$codex_external/agents" ]

    local agents_target="$CX_DIR/symlinked-agents"
    local agents_external="$CX_DIR/external-agents"
    mkdir -p "$agents_target/.codex" "$agents_external"
    printf '%s\n' 'keep agents sentinel' > "$agents_external/sentinel.txt"
    find "$agents_external" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/agents-external.before"
    ln -s "$agents_external" "$agents_target/.codex/agents"

    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$agents_target"
    [ "$status" -ne 0 ]
    find "$agents_external" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/agents-external.after"
    cmp "$CX_LOG_DIR/agents-external.before" "$CX_LOG_DIR/agents-external.after"
    [ "$(find "$agents_external" -type f | wc -l | xargs)" -eq 1 ]
}

@test "codex: native agent sync preserves destination and stale symlinks" {
    local target_dir="$CX_DIR/agent-symlinks"
    local agents_dir="$target_dir/.codex/agents"
    local dangling_target="$CX_DIR/external-missing-agent.toml"
    local external_sentinel="$CX_DIR/external-managed-agent.toml"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir" >/dev/null

    cat > "$external_sentinel" <<'TOML'
# Generated by ai-toolkit. Do not edit.
# ai-toolkit-managed: codex-agent
name = "external-sentinel"
description = "External managed-looking sentinel."
developer_instructions = "Never modify or remove this file."
TOML
    shasum "$external_sentinel" > "$CX_LOG_DIR/external-managed.before"
    ln -s "$external_sentinel" "$agents_dir/ai-toolkit-retired.toml"
    rm "$agents_dir/ai-toolkit-backend-specialist.toml"
    ln -s "$dangling_target" "$agents_dir/ai-toolkit-backend-specialist.toml"

    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir"
    [ "$status" -eq 0 ]
    [ -L "$agents_dir/ai-toolkit-retired.toml" ]
    [ -L "$agents_dir/ai-toolkit-backend-specialist.toml" ]
    [ ! -e "$dangling_target" ]
    shasum "$external_sentinel" > "$CX_LOG_DIR/external-managed.after"
    cmp "$CX_LOG_DIR/external-managed.before" "$CX_LOG_DIR/external-managed.after"
}

@test "codex: staging failure preserves managed files and skips stale cleanup" {
    local target_dir="$CX_DIR/atomic-failure"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir" >/dev/null

    run python3 - "$TOOLKIT_DIR" "$target_dir" <<'PY'
import importlib.util
import os
import sys
from pathlib import Path
from unittest import mock

toolkit = Path(sys.argv[1])
target = Path(sys.argv[2])
sys.path.insert(0, str(toolkit / "scripts"))
spec = importlib.util.spec_from_file_location(
    "generate_codex_agents", toolkit / "scripts" / "generate_codex_agents.py"
)
module = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(module)

agents_dir = target / ".codex" / "agents"
protected = agents_dir / "ai-toolkit-ai-engineer.toml"
protected.write_text(
    "# Generated by ai-toolkit. Do not edit.\n"
    "# ai-toolkit-managed: codex-agent\n"
    'name = "ai-engineer"\n'
    'description = "Previous valid managed agent."\n'
    'developer_instructions = "Preserve until all staging succeeds."\n',
    encoding="utf-8",
)
stale = agents_dir / "ai-toolkit-retired.toml"
stale.write_text(
    "# Generated by ai-toolkit. Do not edit.\n"
    "# ai-toolkit-managed: codex-agent\n"
    'name = "retired"\n'
    'description = "Stale managed fixture."\n'
    'developer_instructions = "Cleanup only after successful replacement."\n',
    encoding="utf-8",
)
before = {path.name: path.read_bytes() for path in agents_dir.glob("*.toml")}
real_fsync = os.fsync
calls = 0

def fail_second_fsync(fd):
    global calls
    calls += 1
    if calls == 2:
        raise OSError("injected staging failure")
    return real_fsync(fd)

try:
    with mock.patch("os.fsync", side_effect=fail_second_fsync):
        module.generate(target)
except OSError as error:
    assert "injected staging failure" in str(error)
else:
    raise AssertionError("expected injected staging failure")

after = {path.name: path.read_bytes() for path in agents_dir.glob("*.toml")}
assert after == before
assert not list(agents_dir.glob(".*.tmp"))
PY
    [ "$status" -eq 0 ]
}

@test "codex: agent body recognizes only standalone frontmatter delimiters" {
    run python3 - "$TOOLKIT_DIR" "$CX_DIR/frontmatter-body.md" <<'PY'
import importlib.util
import sys
from pathlib import Path

toolkit = Path(sys.argv[1])
fixture = Path(sys.argv[2])
sys.path.insert(0, str(toolkit / "scripts"))
spec = importlib.util.spec_from_file_location(
    "generate_codex_agents", toolkit / "scripts" / "generate_codex_agents.py"
)
module = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(module)

fixture.write_text("plain --- body with a second --- separator\n", encoding="utf-8")
assert module._agent_body(fixture) == "plain --- body with a second --- separator\n"
fixture.write_text(
    "---\nname: fixture\ndescription: fixture\n---\n"
    "body with inline --- separator\n",
    encoding="utf-8",
)
assert module._agent_body(fixture) == "body with inline --- separator\n"
PY
    [ "$status" -eq 0 ]
}

# ── generate_codex_hooks.py ─────────────────────────────────────────────────

@test "codex: hooks generator exits 0" {
    [ "$(cat "$CX_LOG_DIR/codex-hooks.status")" = "0" ]
}

@test "codex: hooks.json is valid JSON" {
    run python3 -c "import json; json.load(open('$CX_DIR/.codex/hooks.json'))"
    [ "$status" -eq 0 ]
}

@test "codex: hooks.json never exports the Claude-only output filter" {
    ! grep -q "filter-tool-output" "$CX_DIR/.codex/hooks.json"
}

@test "codex: hooks.json uses only upstream-supported event names (10 events)" {
    # Per codex-rs/config/src/hook_config.rs HookEventName the accepted keys
    # are the 10 below. Verify no unsupported event sneaks in.
    run python3 -c "
import json
supported = {'PreToolUse','PostToolUse','PermissionRequest','PreCompact','PostCompact','SessionStart','UserPromptSubmit','SubagentStart','SubagentStop','Stop'}
data = json.load(open('$CX_DIR/.codex/hooks.json'))
events = set(data['hooks'].keys())
extra = events - supported
assert not extra, f'unsupported events: {extra}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: hooks.json wires the full lifecycle (compaction + subagent events)" {
    # Regression: earlier versions wired only 5 of 10 events. All native+default.
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
for evt in ('PostToolUse','SubagentStart','SubagentStop','PreCompact'):
    assert evt in data['hooks'], f'{evt} missing'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: hooks.json includes PermissionRequest (Codex CLI ≥ 0.121.x)" {
    # Regression: earlier versions omitted PermissionRequest.
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
assert 'PermissionRequest' in data['hooks'], 'PermissionRequest missing'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: Bash path guard runs before execution and permission approval" {
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
for event in ('PreToolUse', 'PermissionRequest'):
    commands = [
        hook.get('command', '')
        for group in data['hooks'][event]
        for hook in group.get('hooks', [])
    ]
    matches = [command for command in commands if command.endswith('/guard-path.sh\"')]
    assert len(matches) == 1, (event, commands)
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: every hook entry uses type=command" {
    # We deliberately only emit command handlers — prompt/agent handlers
    # require a different payload shape documented in hook_config.rs.
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
bad = []
for evt, entries in data['hooks'].items():
    for entry in entries:
        for h in entry.get('hooks', []):
            if h.get('type') != 'command':
                bad.append((evt, h.get('type')))
assert not bad, f'non-command handlers: {bad}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: project command paths point at self-contained hook assets" {
    grep -Fq '$(git rev-parse --show-toplevel 2>/dev/null)/.codex/hooks/' \
        "$CX_DIR/.codex/hooks.json"
    ! grep -Fq '.softspark/ai-toolkit/hooks' "$CX_DIR/.codex/hooks.json"
}

@test "codex: generated hooks run in quiet mode" {
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
for entries in data['hooks'].values():
    for entry in entries:
        for hook in entry.get('hooks', []):
            command = hook.get('command', '')
            assert command.startswith('AI_TOOLKIT_HOOK_QUIET=1 '), command
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: UserPromptSubmit stays quiet while preserving side effects" {
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
commands = [
    h.get('command', '')
    for entry in data['hooks']['UserPromptSubmit']
    for h in entry.get('hooks', [])
]
matches = [c for c in commands if c.endswith('/user-prompt-submit.sh\"')]
assert len(matches) == 1, matches
assert 'AI_TOOLKIT_HOOK_QUIET=1' in matches[0], matches[0]
assert 'AI_TOOLKIT_HOOK_FORMAT=json' not in matches[0], matches[0]
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: Pre/PostToolUse entries use the Bash matcher (upstream limitation)" {
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
for evt in ('PreToolUse', 'PostToolUse'):
    for entry in data['hooks'].get(evt, []):
        assert entry.get('matcher') == 'Bash', f'{evt} matcher != Bash: {entry}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

# ── generate_codex.py (AGENTS.md) ───────────────────────────────────────────

@test "codex: generate_codex.py exits 0" {
    [ "$(cat "$CX_LOG_DIR/codex-md.status")" = "0" ]
}

@test "codex: shared AGENTS.md core is compact and omits discovery catalogs" {
    [ "$(wc -c < "$CX_LOG_DIR/codex-md" | xargs)" -lt 32768 ]
    ! grep -q '^## Available Agents' "$CX_LOG_DIR/codex-md"
    ! grep -q '^## Available Skills' "$CX_LOG_DIR/codex-md"
}

@test "codex: AGENTS.md propagates the source constitution" {
    for phrase in \
        'Article I: Safety First' \
        'Section 4: Autonomous Loop Limits' \
        'Section 5: Proactive Context Checkpointing' \
        'Article VII: Epistemic & Injection Integrity'; do
        grep -q "$phrase" "$CX_LOG_DIR/codex-md" || {
            echo "missing constitution content: $phrase"
            return 1
        }
    done
}

@test "codex: AGENTS.md wraps content in TOOLKIT markers" {
    grep -q '<!-- TOOLKIT:ai-toolkit START -->' "$CX_LOG_DIR/codex-md"
    grep -q '<!-- TOOLKIT:ai-toolkit END -->' "$CX_LOG_DIR/codex-md"
}

@test "codex: AGENTS.md identifies the shared instruction core" {
    grep -q '^# AI Toolkit Instructions' "$CX_LOG_DIR/codex-md"
}

# ── universal coding rules in AGENTS.md ─────────────────────────────────────

@test "codex: AGENTS.md inlines the universal coding rules (Codex reads only AGENTS.md)" {
    # Codex does not read .agents/rules/; the rule bodies must live in AGENTS.md.
    grep -q '^## Coding Rules' "$CX_LOG_DIR/codex-md"
    for h in 'Code Style' 'Testing' 'Security' 'Output Mode'; do
        grep -q "^### $h" "$CX_LOG_DIR/codex-md" || { echo "missing rule: $h"; return 1; }
    done
    grep -qi 'parameterized queries' "$CX_LOG_DIR/codex-md"
}

# ── ecosystem registry integrity ────────────────────────────────────────────

@test "codex: registry declares all codex generators" {
    run python3 -c "
import json
d = json.load(open('$TOOLKIT_DIR/scripts/ecosystem_tools.json'))
entries = [t for t in d['tools'] if t['id'] == 'codex-cli']
assert len(entries) == 1
gens = set(entries[0]['our_generators'])
expected = {
    'scripts/generate_codex.py',
    'scripts/generate_codex_agents.py',
    'scripts/generate_codex_hooks.py',
    'scripts/generate_codex_skills.py',
}
missing = expected - gens
assert not missing, f'registry missing generators: {missing}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}
