#!/usr/bin/env bats
# Codex CLI generator smoke tests.
# Verifies our generators produce output shapes that match the Codex CLI
# upstream contract (codex-rs/config/src/hook_config.rs, docs/agents_md.md).
#
# Run with: bats tests/test_codex.bats

TOOLKIT_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"

setup_file() {
    export CX_DIR; CX_DIR="$(mktemp -d)"
    export CX_LOG_DIR; CX_LOG_DIR="$(mktemp -d)"
    python3 "$TOOLKIT_DIR/scripts/generate_codex.py" > "$CX_LOG_DIR/codex-md" 2>/dev/null
    echo $? > "$CX_LOG_DIR/codex-md.status"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_hooks.py" "$CX_DIR" > "$CX_LOG_DIR/codex-hooks.log" 2>/dev/null
    echo $? > "$CX_LOG_DIR/codex-hooks.status"
}

teardown_file() {
    rm -rf "$CX_DIR" "$CX_LOG_DIR"
}

@test "codex: native agent generator emits the required TOML schema" {
    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR"
    [ "$status" -eq 0 ]

    run python3 - "$TOOLKIT_DIR" "$CX_DIR" <<'PY'
import sys
import tomllib
from pathlib import Path

toolkit = Path(sys.argv[1])
target = Path(sys.argv[2]) / ".codex" / "agents"
sources = sorted((toolkit / "app" / "agents").glob("*.md"))
generated = sorted(target.glob("ai-toolkit-*.toml"))
assert len(generated) == len(sources), (len(generated), len(sources))

for source, output in zip(sources, generated, strict=True):
    data = tomllib.loads(output.read_text(encoding="utf-8"))
    assert set(data) == {"name", "description", "developer_instructions"}, data
    text = source.read_text(encoding="utf-8")
    frontmatter, body = text.split("---", 2)[1:]
    fields = {}
    for line in frontmatter.splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fields[key] = value.strip().strip('"').strip("'")
    assert data["name"] == fields["name"]
    assert data["description"] == fields["description"]
    assert data["developer_instructions"] == body.lstrip("\n").rstrip() + "\n"
    assert output.name == f"ai-toolkit-{data['name']}.toml"
PY
    [ "$status" -eq 0 ]
}

@test "codex: native agent sync preserves user files and cleans only managed stale files" {
    local agents_dir="$CX_DIR/.codex/agents"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR" >/dev/null

    cat > "$agents_dir/ai-toolkit-backend-specialist.toml" <<'TOML'
name = "user-backend"
description = "User-owned collision."
developer_instructions = "Keep this file unchanged."
TOML
    cp "$agents_dir/ai-toolkit-backend-specialist.toml" "$CX_LOG_DIR/user-collision.toml"
    printf '%s\n' 'name = "user-agent"' > "$agents_dir/user-agent.toml"
    printf '%s\n' 'name = "prefixed-user"' > "$agents_dir/ai-toolkit-prefixed-user.toml"
    cat > "$agents_dir/ai-toolkit-retired.toml" <<'TOML'
# Generated by ai-toolkit. Do not edit.
# ai-toolkit-managed: codex-agent
name = "retired"
description = "Stale managed fixture."
developer_instructions = "Remove this file."
TOML

    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR"
    [ "$status" -eq 0 ]
    cmp "$CX_LOG_DIR/user-collision.toml" "$agents_dir/ai-toolkit-backend-specialist.toml"
    [ -f "$agents_dir/user-agent.toml" ]
    [ -f "$agents_dir/ai-toolkit-prefixed-user.toml" ]
    [ ! -e "$agents_dir/ai-toolkit-retired.toml" ]
    grep -q '^# ai-toolkit-managed: codex-agent$' \
        "$agents_dir/ai-toolkit-code-reviewer.toml"

    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/agents.first"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$CX_DIR" >/dev/null
    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/agents.second"
    cmp "$CX_LOG_DIR/agents.first" "$CX_LOG_DIR/agents.second"
}

@test "codex: unmanaged logical name collision wins over managed toolkit agent" {
    local target_dir="$CX_DIR/logical-name-collision"
    local agents_dir="$target_dir/.codex/agents"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir" >/dev/null

    cat > "$agents_dir/custom.toml" <<'TOML'
name = "backend-specialist"
description = "User-owned backend agent."
developer_instructions = "Keep this file unchanged."
TOML
    printf '%s\n' 'name = "invalid-user-agent' > "$agents_dir/invalid-user.toml"
    cp "$agents_dir/custom.toml" "$CX_LOG_DIR/custom-agent.toml"
    cp "$agents_dir/invalid-user.toml" "$CX_LOG_DIR/invalid-user.toml"

    run python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir"
    [ "$status" -eq 0 ]
    cmp "$CX_LOG_DIR/custom-agent.toml" "$agents_dir/custom.toml"
    cmp "$CX_LOG_DIR/invalid-user.toml" "$agents_dir/invalid-user.toml"
    [ ! -e "$agents_dir/ai-toolkit-backend-specialist.toml" ]

    run python3 - "$agents_dir" <<'PY'
import sys
import tomllib
from pathlib import Path

matching = []
for path in Path(sys.argv[1]).glob("*.toml"):
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        continue
    if data.get("name") == "backend-specialist":
        matching.append(path.name)
assert matching == ["custom.toml"], matching
PY
    [ "$status" -eq 0 ]

    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/logical.first"
    python3 "$TOOLKIT_DIR/scripts/generate_codex_agents.py" "$target_dir" >/dev/null
    find "$agents_dir" -type f -exec shasum {} \; | sort > "$CX_LOG_DIR/logical.second"
    cmp "$CX_LOG_DIR/logical.first" "$CX_LOG_DIR/logical.second"
}

# ── generate_codex_hooks.py ─────────────────────────────────────────────────

@test "codex: hooks generator exits 0" {
    [ "$(cat "$CX_LOG_DIR/codex-hooks.status")" = "0" ]
}

@test "codex: hooks.json is valid JSON" {
    run python3 -c "import json; json.load(open('$CX_DIR/.codex/hooks.json'))"
    [ "$status" -eq 0 ]
}

@test "codex: hooks.json uses only upstream-supported event names (10 events)" {
    # Per codex-rs/config/src/hook_config.rs HookEventName the accepted keys
    # are the 10 below. Verify no unsupported event sneaks in.
    run python3 -c "
import json
supported = {'PreToolUse','PostToolUse','PermissionRequest','PreCompact','PostCompact','SessionStart','UserPromptSubmit','SubagentStart','SubagentStop','Stop'}
data = json.load(open('$CX_DIR/.codex/hooks.json'))
events = set(data['hooks'].keys())
extra = events - supported
assert not extra, f'unsupported events: {extra}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: hooks.json wires the full lifecycle (compaction + subagent events)" {
    # Regression: earlier versions wired only 5 of 10 events. All native+default.
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
for evt in ('PostToolUse','SubagentStart','SubagentStop','PreCompact'):
    assert evt in data['hooks'], f'{evt} missing'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: hooks.json includes PermissionRequest (Codex CLI ≥ 0.121.x)" {
    # Regression: earlier versions omitted PermissionRequest.
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
assert 'PermissionRequest' in data['hooks'], 'PermissionRequest missing'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: every hook entry uses type=command" {
    # We deliberately only emit command handlers — prompt/agent handlers
    # require a different payload shape documented in hook_config.rs.
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
bad = []
for evt, entries in data['hooks'].items():
    for entry in entries:
        for h in entry.get('hooks', []):
            if h.get('type') != 'command':
                bad.append((evt, h.get('type')))
assert not bad, f'non-command handlers: {bad}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: command paths point at the shared toolkit hooks directory" {
    grep -q '.softspark/ai-toolkit/hooks' "$CX_DIR/.codex/hooks.json"
}

@test "codex: generated hooks run in quiet mode" {
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
for entries in data['hooks'].values():
    for entry in entries:
        for hook in entry.get('hooks', []):
            command = hook.get('command', '')
            assert command.startswith('AI_TOOLKIT_HOOK_QUIET=1 '), command
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: UserPromptSubmit stays quiet while preserving side effects" {
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
commands = [
    h.get('command', '')
    for entry in data['hooks']['UserPromptSubmit']
    for h in entry.get('hooks', [])
]
matches = [c for c in commands if c.endswith('/user-prompt-submit.sh\"')]
assert len(matches) == 1, matches
assert 'AI_TOOLKIT_HOOK_QUIET=1' in matches[0], matches[0]
assert 'AI_TOOLKIT_HOOK_FORMAT=json' not in matches[0], matches[0]
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "codex: Pre/PostToolUse entries use the Bash matcher (upstream limitation)" {
    run python3 -c "
import json
data = json.load(open('$CX_DIR/.codex/hooks.json'))
for evt in ('PreToolUse', 'PostToolUse'):
    for entry in data['hooks'].get(evt, []):
        assert entry.get('matcher') == 'Bash', f'{evt} matcher != Bash: {entry}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

# ── generate_codex.py (AGENTS.md) ───────────────────────────────────────────

@test "codex: generate_codex.py exits 0" {
    [ "$(cat "$CX_LOG_DIR/codex-md.status")" = "0" ]
}

@test "codex: shared AGENTS.md core is compact and omits discovery catalogs" {
    [ "$(wc -c < "$CX_LOG_DIR/codex-md" | xargs)" -lt 32768 ]
    ! grep -q '^## Available Agents' "$CX_LOG_DIR/codex-md"
    ! grep -q '^## Available Skills' "$CX_LOG_DIR/codex-md"
}

@test "codex: AGENTS.md propagates the source constitution" {
    for phrase in \
        'Article I: Safety First' \
        'Section 4: Autonomous Loop Limits' \
        'Section 5: Proactive Context Checkpointing' \
        'Article VII: Epistemic & Injection Integrity'; do
        grep -q "$phrase" "$CX_LOG_DIR/codex-md" || {
            echo "missing constitution content: $phrase"
            return 1
        }
    done
}

@test "codex: AGENTS.md wraps content in TOOLKIT markers" {
    grep -q '<!-- TOOLKIT:ai-toolkit START -->' "$CX_LOG_DIR/codex-md"
    grep -q '<!-- TOOLKIT:ai-toolkit END -->' "$CX_LOG_DIR/codex-md"
}

@test "codex: AGENTS.md identifies the shared instruction core" {
    grep -q '^# AI Toolkit Instructions' "$CX_LOG_DIR/codex-md"
}

# ── universal coding rules in AGENTS.md ─────────────────────────────────────

@test "codex: AGENTS.md inlines the universal coding rules (Codex reads only AGENTS.md)" {
    # Codex does not read .agents/rules/; the rule bodies must live in AGENTS.md.
    grep -q '^## Coding Rules' "$CX_LOG_DIR/codex-md"
    for h in 'Code Style' 'Testing' 'Security' 'Output Mode'; do
        grep -q "^### $h" "$CX_LOG_DIR/codex-md" || { echo "missing rule: $h"; return 1; }
    done
    grep -qi 'parameterized queries' "$CX_LOG_DIR/codex-md"
}

# ── ecosystem registry integrity ────────────────────────────────────────────

@test "codex: registry declares all codex generators" {
    run python3 -c "
import json
d = json.load(open('$TOOLKIT_DIR/scripts/ecosystem_tools.json'))
entries = [t for t in d['tools'] if t['id'] == 'codex-cli']
assert len(entries) == 1
gens = set(entries[0]['our_generators'])
expected = {
    'scripts/generate_codex.py',
    'scripts/generate_codex_hooks.py',
    'scripts/generate_codex_skills.py',
}
missing = expected - gens
assert not missing, f'registry missing generators: {missing}'
print('ok')
"
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}
