#!/usr/bin/env bats
# Per-tool tests for Augment integration (generate_augment.py + generate_augment_rules.py).
#
# Upstream docs (as of 2026-04-23):
#   https://docs.augmentcode.com/cli/rules.md
#   https://docs.augmentcode.com/cli/hooks.md
#   https://docs.augmentcode.com/cli/subagents.md
#   https://docs.augmentcode.com/cli/skills.md
#   https://docs.augmentcode.com/cli/custom-commands.md
#
# Rules surface we generate:
#   .augment/rules/ai-toolkit-*.md with YAML frontmatter:
#     - type: always_apply | agent_requested
#     - description: <str>
#     - globs: [optional list]
# The Auggie CLI also reads AGENTS.md / CLAUDE.md / .augment/guidelines.md (legacy).
# Surfaces NOT generated by this bucket (tracked as registry markers):
#   - .augment/agents/*.md (subagents, Class F)
#   - .augment/commands/*.md (custom slash commands, Class F)
#   - ~/.augment/settings.json hooks (Class F)
#   - .augment/skills/SKILL.md (agentskills.io compatible, already compatible via app/skills/)

TOOLKIT_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"

setup_file() {
    export AUG_MD_OUT;  AUG_MD_OUT="$(mktemp)"
    export AUG_DIR;     AUG_DIR="$(mktemp -d)"
    python3 "$TOOLKIT_DIR/scripts/generate_augment.py" > "$AUG_MD_OUT" 2>/dev/null
    echo $? > "$AUG_MD_OUT.status"
    python3 "$TOOLKIT_DIR/scripts/generate_augment_rules.py" "$AUG_DIR" > /dev/null 2>&1
    echo $? > "$AUG_MD_OUT.rules-status"
}

teardown_file() {
    rm -f "$AUG_MD_OUT" "$AUG_MD_OUT.status" "$AUG_MD_OUT.rules-status"
    rm -rf "$AUG_DIR"
}

# ── generate_augment.py (single always_apply rule file) ─────────────────────

@test "generate_augment.py exits 0" {
    [ "$(cat "$AUG_MD_OUT.status")" = "0" ]
}

@test "generate_augment.py output is non-empty" {
    [ "$(wc -c < "$AUG_MD_OUT" | xargs)" -gt 500 ]
}

@test "generate_augment.py output has Augment YAML frontmatter" {
    # Frontmatter is emitted inside the toolkit markers; the first `---` line
    # appears after the title. We just ensure the keys exist.
    grep -q '^type: always_apply' "$AUG_MD_OUT"
    grep -q '^description: '      "$AUG_MD_OUT"
}

@test "generate_augment.py output references ai-toolkit attribution" {
    grep -qiE 'ai.?toolkit' "$AUG_MD_OUT"
}

@test "generate_augment.py output lists agent personas section" {
    grep -q '## Available Agent Personas' "$AUG_MD_OUT"
}

@test "generate_augment.py output lists every agent file in app/agents/" {
    local missing=0
    for f in "$TOOLKIT_DIR"/app/agents/*.md; do
        local name="${f##*/}"; name="${name%.md}"
        grep -q "$name" "$AUG_MD_OUT" || missing=$((missing + 1))
    done
    [ "$missing" -eq 0 ]
}

# ── generate_augment_rules.py (per-category rules with frontmatter) ─────────

@test "generate_augment_rules.py exits 0" {
    [ "$(cat "$AUG_MD_OUT.rules-status")" = "0" ]
}

@test "generate_augment_rules.py creates .augment/rules/ directory" {
    [ -d "$AUG_DIR/.augment/rules" ]
}

@test "generate_augment_rules.py emits at least 6 rule files" {
    local count
    count=$(ls "$AUG_DIR/.augment/rules"/ai-toolkit-*.md 2>/dev/null | wc -l | xargs)
    [ "$count" -ge 6 ]
}

@test "augment rules: every file starts with YAML frontmatter" {
    local failed=0
    for f in "$AUG_DIR"/.augment/rules/ai-toolkit-*.md; do
        head -1 "$f" | grep -q '^---$' || failed=$((failed + 1))
    done
    [ "$failed" -eq 0 ]
}

@test "augment rules: frontmatter uses valid type values only" {
    # Per docs (cli/rules.md): `type` must be `always_apply` or `agent_requested`.
    # Catch regressions where we emit unsupported types like `auto` or `manual`
    # (manual is IDE-only; auto is an alias in IDE but not supported in CLI).
    local bad=0
    for f in "$AUG_DIR"/.augment/rules/ai-toolkit-*.md; do
        local type_line
        type_line=$(awk '/^type:/{print $0; exit}' "$f")
        if ! echo "$type_line" | grep -qE '^type:\s*(always_apply|agent_requested)$'; then
            echo "Invalid type in $f: $type_line"
            bad=$((bad + 1))
        fi
    done
    [ "$bad" -eq 0 ]
}

@test "augment rules: testing.md is agent_requested with globs" {
    grep -q '^type: agent_requested' "$AUG_DIR/.augment/rules/ai-toolkit-testing.md"
    grep -q '^globs:' "$AUG_DIR/.augment/rules/ai-toolkit-testing.md"
    grep -q 'test' "$AUG_DIR/.augment/rules/ai-toolkit-testing.md"
}

@test "augment rules: code-style.md is agent_requested with source globs" {
    grep -q '^type: agent_requested' "$AUG_DIR/.augment/rules/ai-toolkit-code-style.md"
    grep -q '^globs:' "$AUG_DIR/.augment/rules/ai-toolkit-code-style.md"
    # Must cover at least python + typescript
    grep -q '"\*\.py"' "$AUG_DIR/.augment/rules/ai-toolkit-code-style.md"
    grep -q '"\*\.ts"' "$AUG_DIR/.augment/rules/ai-toolkit-code-style.md"
}

@test "augment rules: agents-and-skills.md is always_apply" {
    grep -q '^type: always_apply' "$AUG_DIR/.augment/rules/ai-toolkit-agents-and-skills.md"
}

@test "augment rules: description field is present on every rule" {
    local failed=0
    for f in "$AUG_DIR"/.augment/rules/ai-toolkit-*.md; do
        grep -q '^description:' "$f" || failed=$((failed + 1))
    done
    [ "$failed" -eq 0 ]
}

@test "augment rules: agents-and-skills file contains every agent name" {
    local missing=0
    for f in "$TOOLKIT_DIR"/app/agents/*.md; do
        local name="${f##*/}"; name="${name%.md}"
        grep -q "$name" "$AUG_DIR/.augment/rules/ai-toolkit-agents-and-skills.md" || missing=$((missing + 1))
    done
    [ "$missing" -eq 0 ]
}

@test "augment rules: language rules include python when language_modules set" {
    local tmp; tmp="$(mktemp -d)"
    python3 - "$TOOLKIT_DIR" "$tmp" <<'PY'
import sys
from pathlib import Path
sys.path.insert(0, f"{sys.argv[1]}/scripts")
from generate_augment_rules import generate
generate(Path(sys.argv[2]), language_modules=["rules-python"])
PY
    [ -f "$tmp/.augment/rules/ai-toolkit-lang-python.md" ]
    grep -q '^type: agent_requested'    "$tmp/.augment/rules/ai-toolkit-lang-python.md"
    grep -q '"\*\*/\*.py"'              "$tmp/.augment/rules/ai-toolkit-lang-python.md"
    [ -f "$tmp/.augment/rules/ai-toolkit-lang-common.md" ]
    grep -q '^type: always_apply'       "$tmp/.augment/rules/ai-toolkit-lang-common.md"
    rm -rf "$tmp"
}

@test "augment rules: stale toolkit files cleaned on re-run without lang set" {
    local tmp; tmp="$(mktemp -d)"
    python3 - "$TOOLKIT_DIR" "$tmp" <<'PY'
import sys
from pathlib import Path
sys.path.insert(0, f"{sys.argv[1]}/scripts")
from generate_augment_rules import generate
target = Path(sys.argv[2])
generate(target, language_modules=["rules-python"])
generate(target)  # second run without language modules
PY
    [ ! -f "$tmp/.augment/rules/ai-toolkit-lang-python.md" ]
    [ ! -f "$tmp/.augment/rules/ai-toolkit-lang-common.md" ]
    rm -rf "$tmp"
}
