# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Lukasz Krzemien (biuro@softspark.eu)
# Source: https://github.com/softspark/ai-toolkit
"""Uninstall cleanup/discover for Gemini, Antigravity and Augment surfaces.

Every surface is generated by its real generator, then ``discover`` must
count exactly what ``cleanup`` removes, user files must survive, a second
run must be a no-op, and symlinked roots must never be followed.

Run: npm run test:py (pytest, config in pytest.ini).
"""
from __future__ import annotations

import json
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest

SCRIPTS = Path(__file__).resolve().parents[2] / "scripts"
sys.path.insert(0, str(SCRIPTS))

import generate_antigravity  # noqa: E402
import generate_antigravity_agents  # noqa: E402
import generate_antigravity_hooks  # noqa: E402
import generate_augment  # noqa: E402
import generate_augment_agents  # noqa: E402
import generate_augment_commands  # noqa: E402
import generate_augment_hooks  # noqa: E402
import generate_augment_rules  # noqa: E402
import generate_augment_skills  # noqa: E402
import generate_gemini  # noqa: E402
import generate_gemini_agents  # noqa: E402
import generate_gemini_commands  # noqa: E402
import generate_gemini_hooks  # noqa: E402
import generate_gemini_skills  # noqa: E402
from codex_skill_adapter import ADAPTED_MARKER  # noqa: E402

POINTER = "ai-toolkit-skill-catalogue"
USER_TEXT = "user-authored content\n"


def _render(script: str) -> str:
    result = subprocess.run(
        [sys.executable, str(SCRIPTS / script)],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _write(path: Path, content: str = USER_TEXT) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Surface table: (id, setup(target) -> user files, discover, cleanup, scope)
# ---------------------------------------------------------------------------

Setup = Callable[[Path], list[Path]]
Call = Callable[[Path], int]


def _gemini_commands(target: Path) -> list[Path]:
    generate_gemini_commands.generate(target)
    commands = target / ".gemini" / "commands"
    return [
        _write(commands / "mine.toml"),
        # Toolkit prefix but not the generated TOML shape: must survive.
        _write(commands / "ai-toolkit-mine.toml", 'prompt = "mine"\n'),
    ]


def _gemini_skills(target: Path) -> list[Path]:
    generate_gemini_skills.generate(target)
    return [_write(target / ".gemini" / "skills" / "mine" / "SKILL.md")]


def _gemini_agents(target: Path) -> list[Path]:
    generate_gemini_agents.generate(target)
    return [_write(target / ".gemini" / "agents" / "ai-toolkit-mine.md")]


def _antigravity_local(target: Path) -> list[Path]:
    generate_antigravity.generate(target, language_modules=["rules-python"])
    return [
        _write(target / ".agents" / "rules" / "team.md"),
        _write(target / ".agents" / "workflows" / "release.md"),
        _write(target / ".agents" / "skills" / "mine" / "SKILL.md"),
        _write(target / ".agent" / "skills" / "mine" / "SKILL.md"),
    ]


def _antigravity_global(target: Path) -> list[Path]:
    generate_antigravity.generate_global(target)
    return [
        _write(target / ".gemini" / "config" / "skills" / "mine" / "SKILL.md"),
        _write(target / ".gemini" / "antigravity-cli" / "skills" / "mine" / "SKILL.md"),
    ]


def _antigravity_agents_global(target: Path) -> list[Path]:
    generate_antigravity_agents.generate(
        target, config_root=target / ".gemini" / "config"
    )
    return [_write(target / ".gemini" / "config" / "agents" / "mine" / "agent.md")]


def _augment_rules(target: Path) -> list[Path]:
    generate_augment_rules.generate(target, language_modules=["rules-python"])
    rules = target / ".augment" / "rules"
    return [
        _write(rules / "team.md"),
        _write(rules / "ai-toolkit-mine.md", "# no augment frontmatter\n"),
    ]


def _augment_agents(target: Path) -> list[Path]:
    generate_augment_agents.generate(target)
    agents = target / ".augment" / "agents"
    return [
        _write(agents / "mine.md"),
        _write(agents / "ai-toolkit-mine.md", "---\nname: mine\n---\nbody\n"),
    ]


def _augment_commands(target: Path) -> list[Path]:
    generate_augment_commands.generate(target)
    commands = target / ".augment" / "commands"
    return [
        _write(commands / "mine.md"),
        _write(commands / "ai-toolkit-mine.md", "---\nmodel: mine\n---\nbody\n"),
    ]


def _augment_skills(target: Path) -> list[Path]:
    generate_augment_skills.generate(target)
    return [_write(target / ".augment" / "skills" / "mine" / "SKILL.md")]


SURFACES: list[tuple[str, Setup, Call, Call]] = [
    (
        "gemini-commands",
        _gemini_commands,
        generate_gemini_commands.discover,
        generate_gemini_commands.cleanup,
    ),
    (
        "gemini-skills",
        _gemini_skills,
        generate_gemini_skills.discover,
        generate_gemini_skills.cleanup,
    ),
    (
        "gemini-agents",
        _gemini_agents,
        generate_gemini_agents.discover,
        generate_gemini_agents.cleanup,
    ),
    (
        "antigravity-local",
        _antigravity_local,
        generate_antigravity.discover,
        generate_antigravity.cleanup,
    ),
    (
        "antigravity-global",
        _antigravity_global,
        lambda t: generate_antigravity.discover(t, global_install=True),
        lambda t: generate_antigravity.cleanup(t, global_install=True),
    ),
    (
        "antigravity-agents-global",
        _antigravity_agents_global,
        lambda t: generate_antigravity_agents.discover(
            t, config_root=t / ".gemini" / "config"
        ),
        lambda t: generate_antigravity_agents.cleanup(
            t, config_root=t / ".gemini" / "config"
        ),
    ),
    (
        "augment-rules",
        _augment_rules,
        generate_augment_rules.discover,
        generate_augment_rules.cleanup,
    ),
    (
        "augment-agents",
        _augment_agents,
        generate_augment_agents.discover,
        generate_augment_agents.cleanup,
    ),
    (
        "augment-commands",
        _augment_commands,
        generate_augment_commands.discover,
        generate_augment_commands.cleanup,
    ),
    (
        "augment-skills",
        _augment_skills,
        generate_augment_skills.discover,
        generate_augment_skills.cleanup,
    ),
]


@pytest.mark.parametrize(
    ("setup", "discover", "cleanup"),
    [surface[1:] for surface in SURFACES],
    ids=[surface[0] for surface in SURFACES],
)
def test_cleanup_removes_managed_and_keeps_user_files(
    tmp_path: Path, setup: Setup, discover: Call, cleanup: Call
) -> None:
    user_files = setup(tmp_path)
    before = {path: path.read_bytes() for path in user_files}

    found = discover(tmp_path)
    assert found > 0
    assert cleanup(tmp_path) == found

    for path, content in before.items():
        assert path.read_bytes() == content
    assert discover(tmp_path) == 0
    assert cleanup(tmp_path) == 0


def test_cleanup_prunes_only_emptied_directories(tmp_path: Path) -> None:
    generate_antigravity.generate(tmp_path)
    user_rule = _write(tmp_path / ".agents" / "rules" / "team.md")

    assert generate_antigravity.cleanup(tmp_path) > 0

    assert user_rule.is_file()
    assert not (tmp_path / ".agents" / "workflows").exists()
    assert not (tmp_path / ".agents" / "skills").exists()
    assert not (tmp_path / ".agent").exists()
    assert tmp_path.is_dir()


def test_antigravity_counts_rules_workflows_and_both_pointers(tmp_path: Path) -> None:
    generate_antigravity.generate(tmp_path)
    rules = list((tmp_path / ".agents" / "rules").glob("ai-toolkit-*.md"))
    workflows = list((tmp_path / ".agents" / "workflows").glob("ai-toolkit-*.md"))

    assert generate_antigravity.discover(tmp_path) == len(rules) + len(workflows) + 2
    assert generate_antigravity.discover(tmp_path, global_install=True) == 0


def test_antigravity_skips_pointer_owned_by_codex_adapter(tmp_path: Path) -> None:
    generate_antigravity.generate(tmp_path)
    codex_owned = tmp_path / ".agents" / "skills" / POINTER
    _write(codex_owned / ADAPTED_MARKER, "")

    generate_antigravity.cleanup(tmp_path)

    assert (codex_owned / "SKILL.md").is_file()
    assert not (tmp_path / ".agent" / "skills" / POINTER).exists()


# ---------------------------------------------------------------------------
# Shared instruction files with TOOLKIT markers
# ---------------------------------------------------------------------------

MARKER_FILES: list[tuple[str, str, Callable[[Path], Path], Call, Call]] = [
    (
        "gemini-local",
        "generate_gemini.py",
        lambda t: t / "GEMINI.md",
        generate_gemini.discover,
        generate_gemini.cleanup,
    ),
    (
        "gemini-global",
        "generate_gemini.py",
        lambda t: t / ".gemini" / "GEMINI.md",
        lambda t: generate_gemini.discover(t, global_install=True),
        lambda t: generate_gemini.cleanup(t, global_install=True),
    ),
    (
        "augment-global",
        "generate_augment.py",
        lambda t: t / ".augment" / "rules" / "ai-toolkit.md",
        generate_augment.discover,
        generate_augment.cleanup,
    ),
]


@pytest.mark.parametrize(
    ("script", "locate", "discover", "cleanup"),
    [entry[1:] for entry in MARKER_FILES],
    ids=[entry[0] for entry in MARKER_FILES],
)
def test_marker_file_keeps_user_text(
    tmp_path: Path, script: str, locate: Callable[[Path], Path],
    discover: Call, cleanup: Call,
) -> None:
    path = _write(
        locate(tmp_path),
        "# My notes\n\nkeep above\n\n" + _render(script) + "\nkeep below\n",
    )

    assert discover(tmp_path) == 1
    assert cleanup(tmp_path) == 1

    text = path.read_text(encoding="utf-8")
    assert "TOOLKIT:" not in text
    assert text.startswith("# My notes\n")
    assert "keep above" in text
    assert text.endswith("keep below\n")
    assert discover(tmp_path) == 0
    assert cleanup(tmp_path) == 0


@pytest.mark.parametrize(
    ("script", "locate", "discover", "cleanup"),
    [entry[1:] for entry in MARKER_FILES],
    ids=[entry[0] for entry in MARKER_FILES],
)
def test_marker_file_deleted_when_only_toolkit_content(
    tmp_path: Path, script: str, locate: Callable[[Path], Path],
    discover: Call, cleanup: Call,
) -> None:
    path = _write(locate(tmp_path), _render(script))

    assert cleanup(tmp_path) == 1

    assert not path.exists()
    assert discover(tmp_path) == 0


def test_marker_file_without_markers_is_untouched(tmp_path: Path) -> None:
    path = _write(tmp_path / "GEMINI.md", "# Only mine\n")

    assert generate_gemini.discover(tmp_path) == 0
    assert generate_gemini.cleanup(tmp_path) == 0
    assert path.read_text(encoding="utf-8") == "# Only mine\n"


# ---------------------------------------------------------------------------
# Hook configs
# ---------------------------------------------------------------------------

def test_gemini_hooks_strip_only_toolkit_entries(tmp_path: Path) -> None:
    settings = tmp_path / ".gemini" / "settings.json"
    user_hook = {"matcher": "x", "hooks": [{"type": "command", "command": "mine"}]}
    _write(settings, json.dumps({"theme": "dark", "hooks": {"BeforeTool": [user_hook]}}))
    generate_gemini_hooks.generate(tmp_path)

    found = generate_gemini_hooks.discover(tmp_path)
    assert found > 0
    assert generate_gemini_hooks.cleanup(tmp_path) == found

    data = json.loads(settings.read_text(encoding="utf-8"))
    assert data == {"theme": "dark", "hooks": {"BeforeTool": [user_hook]}}
    assert generate_gemini_hooks.discover(tmp_path) == 0
    assert generate_gemini_hooks.cleanup(tmp_path) == 0


def test_gemini_hooks_delete_file_and_prune_when_only_toolkit(tmp_path: Path) -> None:
    generate_gemini_hooks.generate(tmp_path)

    assert generate_gemini_hooks.cleanup(tmp_path) > 0

    assert not (tmp_path / ".gemini").exists()


def test_augment_hooks_strip_only_toolkit_groups(tmp_path: Path) -> None:
    settings = tmp_path / ".augment" / "settings.json"
    user_group = {"matcher": "view", "hooks": [{"type": "command", "command": "mine"}]}
    _write(settings, json.dumps({"model": "x", "hooks": {"PreToolUse": [user_group]}}))
    generate_augment_hooks.generate(tmp_path)

    found = generate_augment_hooks.discover(tmp_path)
    assert found == sum(len(v) for v in generate_augment_hooks.AUGMENT_HOOKS.values())
    assert generate_augment_hooks.cleanup(tmp_path) == found

    data = json.loads(settings.read_text(encoding="utf-8"))
    assert data == {"model": "x", "hooks": {"PreToolUse": [user_group]}}
    assert generate_augment_hooks.discover(tmp_path) == 0
    assert generate_augment_hooks.cleanup(tmp_path) == 0


def test_augment_hooks_delete_file_when_only_toolkit(tmp_path: Path) -> None:
    generate_augment_hooks.generate(tmp_path)

    assert generate_augment_hooks.cleanup(tmp_path) > 0

    assert not (tmp_path / ".augment").exists()


def test_augment_hooks_leave_invalid_json_alone(tmp_path: Path) -> None:
    settings = _write(tmp_path / ".augment" / "settings.json", "{not json")

    assert generate_augment_hooks.discover(tmp_path) == 0
    assert generate_augment_hooks.cleanup(tmp_path) == 0
    assert settings.read_text(encoding="utf-8") == "{not json"


@pytest.mark.parametrize("global_install", [False, True], ids=["local", "global"])
def test_antigravity_hooks_remove_namespace_and_runtime(
    tmp_path: Path, global_install: bool
) -> None:
    hooks_path = generate_antigravity_hooks.generate(
        tmp_path, global_install=global_install
    )
    document = json.loads(hooks_path.read_text(encoding="utf-8"))
    document["user"] = {"Stop": [{"command": "mine", "timeout": 5}]}
    hooks_path.write_text(json.dumps(document), encoding="utf-8")

    assert generate_antigravity_hooks.discover(
        tmp_path, global_install=global_install
    ) == 2
    assert generate_antigravity_hooks.cleanup(
        tmp_path, global_install=global_install
    ) == 2

    assert json.loads(hooks_path.read_text(encoding="utf-8")) == {
        "user": {"Stop": [{"command": "mine", "timeout": 5}]}
    }
    assert not (hooks_path.parent / "hooks").exists()
    assert generate_antigravity_hooks.cleanup(
        tmp_path, global_install=global_install
    ) == 0


def test_antigravity_hooks_remove_orphaned_runtime(tmp_path: Path) -> None:
    hooks_path = generate_antigravity_hooks.generate(tmp_path)
    hooks_path.unlink()

    assert generate_antigravity_hooks.discover(tmp_path) == 1
    assert generate_antigravity_hooks.cleanup(tmp_path) == 1
    assert not (tmp_path / ".agents" / "hooks").exists()


def test_antigravity_hooks_keep_user_runtime(tmp_path: Path) -> None:
    runtime = _write(
        tmp_path / ".agents" / "hooks" / generate_antigravity_hooks.RUNTIME_NAME
    )

    assert generate_antigravity_hooks.discover(tmp_path) == 0
    assert generate_antigravity_hooks.cleanup(tmp_path) == 0
    assert runtime.read_text(encoding="utf-8") == USER_TEXT


# ---------------------------------------------------------------------------
# Symlinks are never followed
# ---------------------------------------------------------------------------

SymlinkCase = tuple[str, str, Setup, Call, Call]


def _link_setup(tmp_path: Path, relative: str, setup: Setup) -> tuple[Path, Path]:
    """Generate into ``outside`` and expose ``relative`` as a symlink to it."""
    outside = tmp_path / "outside"
    outside.mkdir()
    setup(outside)
    target = tmp_path / "target"
    link = target / relative
    link.parent.mkdir(parents=True)
    link.symlink_to(outside / relative, target_is_directory=True)
    return target, outside / relative


SYMLINKED_ROOTS: list[SymlinkCase] = [
    (
        "gemini-commands",
        ".gemini/commands",
        _gemini_commands,
        generate_gemini_commands.discover,
        generate_gemini_commands.cleanup,
    ),
    (
        "gemini-skills",
        ".gemini/skills",
        _gemini_skills,
        generate_gemini_skills.discover,
        generate_gemini_skills.cleanup,
    ),
    (
        "gemini-agents-parent",
        ".gemini",
        _gemini_agents,
        generate_gemini_agents.discover,
        generate_gemini_agents.cleanup,
    ),
    (
        "antigravity-rules",
        ".agents/rules",
        _antigravity_local,
        generate_antigravity.discover,
        generate_antigravity.cleanup,
    ),
    (
        "antigravity-global-skills",
        ".gemini/config",
        _antigravity_global,
        lambda t: generate_antigravity.discover(t, global_install=True),
        lambda t: generate_antigravity.cleanup(t, global_install=True),
    ),
    (
        "antigravity-agents",
        ".gemini/config",
        _antigravity_agents_global,
        lambda t: generate_antigravity_agents.discover(
            t, config_root=t / ".gemini" / "config"
        ),
        lambda t: generate_antigravity_agents.cleanup(
            t, config_root=t / ".gemini" / "config"
        ),
    ),
    (
        "augment-rules",
        ".augment/rules",
        _augment_rules,
        generate_augment_rules.discover,
        generate_augment_rules.cleanup,
    ),
    (
        "augment-agents",
        ".augment",
        _augment_agents,
        generate_augment_agents.discover,
        generate_augment_agents.cleanup,
    ),
    (
        "augment-commands",
        ".augment/commands",
        _augment_commands,
        generate_augment_commands.discover,
        generate_augment_commands.cleanup,
    ),
    (
        "augment-skills",
        ".augment/skills",
        _augment_skills,
        generate_augment_skills.discover,
        generate_augment_skills.cleanup,
    ),
]


def _snapshot(root: Path) -> dict[str, bytes]:
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


@pytest.mark.parametrize(
    ("relative", "setup", "discover", "cleanup"),
    [case[1:] for case in SYMLINKED_ROOTS],
    ids=[case[0] for case in SYMLINKED_ROOTS],
)
def test_symlinked_root_is_refused(
    tmp_path: Path, relative: str, setup: Setup, discover: Call, cleanup: Call
) -> None:
    target, linked = _link_setup(tmp_path, relative, setup)
    before = _snapshot(linked)

    with pytest.raises(RuntimeError):
        discover(target)
    with pytest.raises(RuntimeError):
        cleanup(target)

    assert _snapshot(linked) == before


def test_symlinked_target_is_refused(tmp_path: Path) -> None:
    real = tmp_path / "real"
    generate_augment_skills.generate(real)
    link = tmp_path / "link"
    link.symlink_to(real, target_is_directory=True)

    with pytest.raises(RuntimeError):
        generate_augment_skills.cleanup(link)
    assert (real / ".augment" / "skills" / POINTER / "SKILL.md").is_file()


@pytest.mark.parametrize(
    ("skills_root", "discover", "cleanup"),
    [
        (".gemini/skills", generate_gemini_skills.discover, generate_gemini_skills.cleanup),
        (".augment/skills", generate_augment_skills.discover, generate_augment_skills.cleanup),
        (".agent/skills", generate_antigravity.discover, generate_antigravity.cleanup),
    ],
    ids=["gemini", "augment", "antigravity"],
)
def test_symlinked_pointer_directory_is_skipped(
    tmp_path: Path, skills_root: str, discover: Call, cleanup: Call
) -> None:
    outside = tmp_path / "outside"
    generate_augment_skills.generate(outside)
    pointer = outside / ".augment" / "skills" / POINTER / "SKILL.md"
    target = tmp_path / "target"
    link = target / skills_root / POINTER
    link.parent.mkdir(parents=True)
    link.symlink_to(pointer.parent, target_is_directory=True)

    assert discover(target) == 0
    assert cleanup(target) == 0
    assert pointer.is_file()
    assert link.is_symlink()


@pytest.mark.parametrize(
    ("hooks_file", "discover", "cleanup"),
    [
        (".gemini/settings.json", generate_gemini_hooks.discover, generate_gemini_hooks.cleanup),
        (".augment/settings.json", generate_augment_hooks.discover, generate_augment_hooks.cleanup),
    ],
    ids=["gemini", "augment"],
)
def test_symlinked_settings_file_is_skipped(
    tmp_path: Path, hooks_file: str, discover: Call, cleanup: Call
) -> None:
    outside = tmp_path / "outside"
    if hooks_file.startswith(".gemini"):
        real = generate_gemini_hooks.generate(outside)
    else:
        real = generate_augment_hooks.generate(outside)
    before = real.read_bytes()
    target = tmp_path / "target"
    link = target / hooks_file
    link.parent.mkdir(parents=True)
    link.symlink_to(real)

    assert discover(target) == 0
    assert cleanup(target) == 0
    assert real.read_bytes() == before


def test_symlinked_gemini_dir_is_skipped_for_hooks(tmp_path: Path) -> None:
    outside = tmp_path / "outside"
    real = generate_gemini_hooks.generate(outside)
    before = real.read_bytes()
    target = tmp_path / "target"
    target.mkdir()
    (target / ".gemini").symlink_to(real.parent, target_is_directory=True)

    assert generate_gemini_hooks.discover(target) == 0
    assert generate_gemini_hooks.cleanup(target) == 0
    assert real.read_bytes() == before


def test_symlinked_marker_file_is_skipped(tmp_path: Path) -> None:
    outside = _write(tmp_path / "outside.md", _render("generate_gemini.py"))
    target = tmp_path / "target"
    target.mkdir()
    (target / "GEMINI.md").symlink_to(outside)
    before = outside.read_bytes()

    assert generate_gemini.discover(target) == 0
    assert generate_gemini.cleanup(target) == 0
    assert outside.read_bytes() == before


def test_existing_callers_ignore_return_value(tmp_path: Path) -> None:
    """install/uninstall call these as statements; returns must stay ints."""
    results: list[Any] = [
        generate_gemini_hooks.cleanup(tmp_path),
        generate_antigravity_hooks.cleanup(tmp_path),
        generate_antigravity_hooks.cleanup(tmp_path, global_install=True),
        generate_gemini_agents.cleanup(tmp_path),
        generate_antigravity_agents.cleanup(tmp_path),
    ]
    assert results == [0, 0, 0, 0, 0]
