"""Adapt ai-toolkit skills for Codex CLI.

Compatible skills are symlinked as-is. Skills that rely on Claude-only
delegation primitives are rendered into Codex-specific wrappers that keep the
same references/assets but rewrite the main SKILL.md guidance to use native
Codex subagents and plan tracking.
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

try:
    from frontmatter import frontmatter_field
except ModuleNotFoundError:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from frontmatter import frontmatter_field


CLAUDE_ONLY_TOOLS = frozenset({
    "Agent", "TeamCreate", "TeamDelete", "SendMessage",
    "TaskCreate", "TaskList", "TaskUpdate", "TaskGet", "TaskOutput", "TaskStop",
    "Skill", "EnterPlanMode", "ExitPlanMode",
})

CODEX_DELEGATION_TOOLS = (
    "spawn_agent", "send_input", "wait_agent", "close_agent", "update_plan",
)

ADAPTED_MARKER = ".ai-toolkit-codex-adapted"

_FRONTMATTER_RE = re.compile(r"\A---\n(?P<frontmatter>.*?)\n---\n?(?P<body>.*)\Z", re.S)
_SINGLE_AGENT_CALL_RE = re.compile(
    r'Agent\(subagent_type="([^"]+)",\s*prompt="([^"]+)"[^)]*\)'
)
_MULTILINE_AGENT_CALL_RE = re.compile(
    r'Agent\(\s*\n'
    r'\s*subagent_type="([^"]+)"\s*,\s*\n'
    r'\s*description="([^"]+)"\s*,\s*\n'
    r'\s*prompt="([^"]+)"\s*\n'
    r'\)',
    re.S,
)

_CODEX_NOTE = """
## Codex Translation Layer

This generated Codex variant preserves the original workflow while translating
Claude-only delegation primitives into Codex-native ones:

- Use `spawn_agent(..., fork_context=True, ...)` instead of Claude `Agent(...)`.
- Pick `explorer` for read-only discovery, `worker` for edits, `default` for
  synthesis, planning, and mixed execution.
- Use `send_input` to redirect or clarify an active subagent.
- Use `wait_agent` only when the next critical-path step is blocked on a
  delegated result.
- Use `close_agent` after integrating finished subagents.
- Track progress with `update_plan` or a local checklist instead of Claude
  task/team APIs.
- Treat a "team" as a coordinated set of spawned subagents with explicit file
  ownership. No extra Codex feature flag is required.
"""


def skill_tools(skill_file: Path) -> list[str]:
    """Return ordered allowed-tools entries from a skill frontmatter block."""
    tools_str = frontmatter_field(skill_file, "allowed-tools") or ""
    return [tool.strip() for tool in tools_str.split(",") if tool.strip()]


def is_codex_adapted_skill(skill_file: Path) -> bool:
    """Return True if a skill needs Claude→Codex delegation adaptation."""
    return bool(set(skill_tools(skill_file)) & CLAUDE_ONLY_TOOLS)


def codex_skill_description(skill_file: Path) -> str:
    """Return the skill description shown in Codex-facing generators."""
    description = frontmatter_field(skill_file, "description")
    if not description:
        return ""
    if is_codex_adapted_skill(skill_file):
        return f"{description} Codex-adapted: uses native subagents and plan tracking."
    return description


def build_codex_skill_text(skill_file: Path) -> str:
    """Render the Codex-facing SKILL.md contents for a source skill."""
    text = skill_file.read_text(encoding="utf-8")
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return text

    frontmatter = _parse_frontmatter(match.group("frontmatter"))
    body = match.group("body")
    adapted = is_codex_adapted_skill(skill_file)

    if adapted:
        frontmatter = _adapt_frontmatter(frontmatter)
        body = _adapt_body(skill_file.parent.name, body)

    rendered_frontmatter = _render_frontmatter(frontmatter)
    return f"---\n{rendered_frontmatter}\n---\n{body.rstrip()}\n"


def sync_codex_skill(skill_dir: Path, skills_dst: Path) -> str:
    """Install one skill into `.agents/skills/` and return its mode."""
    skill_file = skill_dir / "SKILL.md"
    target = skills_dst / skill_dir.name
    adapted = is_codex_adapted_skill(skill_file)
    marker = target / ADAPTED_MARKER

    if adapted:
        if target.is_symlink():
            target.unlink()
        elif target.is_dir() and not marker.is_file():
            return "skipped"
        elif target.is_dir():
            shutil.rmtree(target)
        elif target.exists():
            return "skipped"

        target.mkdir(parents=True, exist_ok=True)
        marker.write_text("generated by ai-toolkit for Codex\n", encoding="utf-8")

        for child in sorted(skill_dir.iterdir()):
            dest = target / child.name
            if child.name == "SKILL.md":
                continue
            if dest.is_symlink() or dest.is_file():
                dest.unlink()
            elif dest.is_dir():
                shutil.rmtree(dest)
            dest.symlink_to(child)

        (target / "SKILL.md").write_text(build_codex_skill_text(skill_file), encoding="utf-8")
        return "adapted"

    if target.is_symlink():
        if target.resolve() == skill_dir.resolve():
            return "linked"
        target.unlink()
    elif target.is_dir():
        if marker.is_file():
            shutil.rmtree(target)
        else:
            return "skipped"
    elif target.exists():
        return "skipped"

    target.symlink_to(skill_dir)
    return "linked"


def cleanup_codex_skills(skills_dst: Path, skills_src: Path) -> None:
    """Remove broken symlinks and stale generated Codex skill wrappers."""
    skills_src_resolved = skills_src.resolve()
    for item in skills_dst.iterdir():
        src = skills_src / item.name
        if item.is_symlink():
            if not item.exists():
                item.unlink()
                continue
            target = item.resolve()
            if src.is_dir() and target == src.resolve():
                continue
            if _is_relative_to(target, skills_src_resolved):
                item.unlink()
                continue
        if item.is_dir() and (item / ADAPTED_MARKER).is_file() and not src.is_dir():
            shutil.rmtree(item)


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def _parse_frontmatter(frontmatter_text: str) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for line in frontmatter_text.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        entries.append((key.strip(), value.strip()))
    return entries


def _render_frontmatter(entries: list[tuple[str, str]]) -> str:
    return "\n".join(f"{key}: {value}" for key, value in entries)


def _adapt_frontmatter(entries: list[tuple[str, str]]) -> list[tuple[str, str]]:
    adapted: list[tuple[str, str]] = []
    for key, value in entries:
        if key in {"context", "agent", "model"}:
            continue
        if key == "description":
            stripped = _strip_quotes(value)
            value = f'"{stripped} Codex-adapted: uses native subagents and plan tracking."'
        elif key == "allowed-tools":
            value = ", ".join(_adapt_allowed_tools(value))
        adapted.append((key, value))
    return adapted


def _adapt_allowed_tools(value: str) -> list[str]:
    tools = []
    for tool in [item.strip() for item in value.split(",") if item.strip()]:
        if tool in CLAUDE_ONLY_TOOLS:
            continue
        if tool not in tools:
            tools.append(tool)
    for tool in CODEX_DELEGATION_TOOLS:
        if tool not in tools:
            tools.append(tool)
    return tools


def _adapt_body(skill_name: str, body: str) -> str:
    body = body.replace(
        "## MANDATORY: You MUST use the Agent tool",
        "## MANDATORY: Use Codex subagents for delegation",
    )
    body = body.replace("`Agent` tool", "Codex subagent tools")
    body = body.replace("the `Agent` tool", "Codex subagent tools")
    body = body.replace("Agent tool", "Codex subagent tools")
    body = body.replace("Agent Teams", "parallel Codex subagents")
    body = body.replace(
        "Requires: `CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1`",
        "Requires: native Codex subagent support (`spawn_agent`, `send_input`, `wait_agent`, `close_agent`)",
    )
    body = body.replace(
        "Check `CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS` is set; warn if not",
        "Confirm the user explicitly wants delegated/subagent execution before launching workers",
    )
    body = body.replace(
        "export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1",
        "# No extra environment variable is required in Codex",
    )
    body = body.replace("TaskCreate", "update_plan")
    body = body.replace("TaskList", "update_plan")
    body = body.replace("TaskUpdate", "update_plan")
    body = body.replace("TaskGet", "wait_agent")
    body = body.replace("TaskOutput", "wait_agent")
    body = body.replace("TaskStop", "close_agent")
    body = body.replace("SendMessage", "send_input")
    body = body.replace("TeamCreate", "spawn_agent")
    body = body.replace("TeamDelete", "close_agent")

    body = _MULTILINE_AGENT_CALL_RE.sub(_replace_multiline_agent_call, body)
    body = _SINGLE_AGENT_CALL_RE.sub(_replace_single_agent_call, body)

    if "$ARGUMENTS" in body:
        body = body.replace("$ARGUMENTS", f"$ARGUMENTS\n{_CODEX_NOTE.rstrip()}", 1)

    if skill_name == "teams":
        body = body.replace(
            "Launches a pre-configured Agent Teams composition for your task.",
            "Launches a pre-configured Codex subagent composition for your task.",
        )
    return body


def _replace_single_agent_call(match: re.Match[str]) -> str:
    role = match.group(1)
    prompt = match.group(2)
    agent_type = _codex_agent_type(role, prompt)
    escaped_prompt = prompt.replace('"', "'")
    return (
        f'spawn_agent(agent_type="{agent_type}", fork_context=True, '
        f'message="Act as {role}. {escaped_prompt}")'
    )


def _replace_multiline_agent_call(match: re.Match[str]) -> str:
    role = match.group(1)
    prompt = match.group(3).replace('"', "'")
    return (
        "spawn_agent(\n"
        f'  agent_type="{_codex_agent_type(role, prompt)}",\n'
        "  fork_context=True,\n"
        f'  message="Act as {role}. {prompt}"\n'
        ")"
    )


def _codex_agent_type(role: str, prompt: str) -> str:
    role_l = role.lower()
    prompt_l = prompt.lower()
    if role_l == "explorer-agent":
        return "explorer"
    if any(token in prompt_l for token in ("read-only", "review", "audit", "trace", "map ", "analyze")):
        return "default"
    if any(token in prompt_l for token in (
        "own files:", "implement", "write ", "apply", "build ", "update ",
        "create ", "execute ", "fix", "document", "deploy",
    )):
        return "worker"
    return "default"


def _strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value
