#!/usr/bin/env python3
"""Generate .aider.conf.yml configuration.

Usage: ./scripts/generate_aider_conf.py > .aider.conf.yml
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _common import DEFAULT_CLAUDE_MODELS


def main() -> None:
    default_model = DEFAULT_CLAUDE_MODELS["sonnet"]
    print("# Aider configuration generated by ai-toolkit")
    print("# Regenerate using: ai-toolkit install --local")
    print()
    print("# Use the architect mode for complex tasks, aligned with our 2-phase workflow")
    print("architect: true")
    print()
    print("# Read project rules (loaded as read-only context)")
    print("read:")
    print('  - "CONVENTIONS.md"')
    print('  - ".claude/CLAUDE.md"')
    print('  - ".claude/constitution.md"')
    print('  - "AGENTS.md"')
    print()
    print("# Linting commands for quality gates")
    print("lint-cmd:")
    print('  - "python: ruff check"')
    print('  - "typescript: npx eslint"')
    print('  - "javascript: npx eslint"')
    print('  - "php: ./vendor/bin/phpstan analyse"')
    print('  - "go: go vet"')
    print()
    print("# Model configuration")
    print(f"model: {default_model}")
    print(f"editor-model: {default_model}")
    print()
    print("# Auto-commit message formatting (matches our conventional commits)")
    print(
        'commit_prompt: "Write a short, concise commit message following'
        ' Conventional Commits (feat/fix/chore/docs/test/refactor)."'
    )
    print()
    print("# Disable auto-commits if you prefer using the /commit slash skill explicitly")
    print("# auto-commits: false")
    print()


if __name__ == "__main__":
    main()
