#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Lukasz Krzemien (biuro@softspark.eu)
# Source: https://github.com/softspark/ai-toolkit

"""Generate Antigravity IDE ``.agents/rules/``, ``.agents/workflows/``, and
skill pointer files.

Antigravity 2.0 reads rules/workflows from the plural ``.agents/`` directory by
default; singular ``.agent/`` is only a legacy fallback. We emit plural.
Antigravity reads rules from:
  * ``GEMINI.md`` (highest priority) — generated by ``generate_gemini.py``
  * ``AGENTS.md`` (cross-tool) — the project's own instructions, not generated
  * ``.agents/rules/*.md`` — per-category rule files (this generator)
  * ``.agents/workflows/*.md`` — workflow templates (this generator)

Every ``.agents/rules/*.md`` file needs ``trigger:`` frontmatter (``always_on``,
``model_decision``, ``glob`` or ``manual``); Antigravity silently discards a rule
without it. Each rule file is truncated above 24,000 bytes, and always-on plus
global rules share a 20,000-token budget, so only a small core is always-on and
the rest load on model decision (antigravity.google/docs/rules/). Registered
rules that depend on an MCP server are emitted only when Antigravity has that
server configured (see ``registered_rules``).

Antigravity also supports the Agent Skills standard at
``.agents/skills/<skill-name>/SKILL.md``. We do not duplicate our full skill
catalogue; instead we emit a pointer skill that teaches Antigravity to look up
the real catalogue in ``.claude/skills/`` or ``~/.claude/skills/``. The legacy
``.agent/skills/`` copy is no longer written, and reinstalling removes the one
an older release left behind.
The 13 standard workflow commands also ship as same-named native skills, since
workflow execution retires on 2026-11-01. Legacy workflow files remain for older
clients; native skills take precedence when both exist.

Usage:
  python3 scripts/generate_antigravity.py [target-dir]

Writes rules/workflows to target-dir/.agents/{rules,workflows}/ and the skill
pointer to target-dir/.agents/skills/.
"""
from __future__ import annotations

import sys
from functools import partial
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from codex_skill_adapter import ADAPTED_MARKER
from antigravity_workflow_skills import (
    owned_workflow_skill_edit,
    sync_workflow_skills,
    workflow_skill_paths,
)
from dir_rules_shared import (
    CUSTOM_PREFIX,
    CUSTOM_SCOPE,
    LANG_GLOBS,
    LANG_PREFIX,
    LANG_SCOPE,
    PREFIX,
    STANDARD_RULES,
    STANDARD_WORKFLOWS,
    build_language_rules,
    rule_scope,
    with_frontmatter,
    write_rules,
)
from emission import emit_agents_bullets, emit_skills_bullets
from frontmatter import FrontmatterError, parse_frontmatter
from registered_rules import ANTIGRAVITY_RULE_LIMIT_BYTES, rule_text, select_rule_files
from rule_sources import load_sources
from secure_fs import OwnedEdit, apply_owned_edits, lexical_absolute
from skill_pointer import owned_pointer_edit


# ---------------------------------------------------------------------------
# Skill pointer — a single SKILL.md that directs Antigravity to our catalogue
# ---------------------------------------------------------------------------

POINTER_SKILL_NAME = "ai-toolkit-skill-catalogue"


def _pointer_skill_md() -> str:
    """Build the SKILL.md body for the pointer skill."""
    body = (
        "# AI Toolkit Skill Catalogue\n\n"
        "This workspace uses the ai-toolkit. Real skills are installed "
        "alongside Claude Code at `.claude/skills/` (project install) or "
        "`~/.claude/skills/` (global install). If the ai-toolkit installer "
        "has run, every skill below already exists as an agent-invocable "
        "SKILL.md on disk.\n\n"
        "## When to use this skill\n\n"
        "- You are asked to run a task that maps to one of the catalogued "
        "skills below.\n"
        "- You want to discover which skills the user has installed before "
        "reinventing the wheel.\n\n"
        "## How to invoke a catalogue entry\n\n"
        "1. Match the user's task to a skill name in the catalogue.\n"
        "2. Read the skill's SKILL.md from `.claude/skills/<name>/SKILL.md` "
        "or `~/.claude/skills/<name>/SKILL.md` (whichever exists).\n"
        "3. Follow its Rules, Gotchas, and When NOT to Use sections.\n"
        "4. Ignore CLAUDE_CODE_ONLY blocks outside Claude Code; use native "
        "agents and the current client's configured models.\n\n"
        "## Catalogue (installed skills)\n\n"
        f"{emit_skills_bullets()}\n"
    )
    return (
        "---\n"
        f"name: {POINTER_SKILL_NAME}\n"
        "description: Index of ai-toolkit skills installed at .claude/skills/"
        " or ~/.claude/skills/. Read this first when the user's request "
        "matches a named skill.\n"
        "---\n"
        f"{body}"
    )


def _write_skill_pointer(target_dir: Path) -> None:
    """Write the pointer SKILL.md to ``.agents/skills/`` and drop the copy an
    older release wrote to the legacy ``.agent/skills/`` tree, which
    Antigravity would otherwise load as a second, shadowed skill."""
    skill_dir = target_dir / ".agents" / "skills" / POINTER_SKILL_NAME
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(_pointer_skill_md(), encoding="utf-8")
    print(f"  Generated: .agents/skills/{POINTER_SKILL_NAME}/SKILL.md")
    legacy_dir = target_dir / ".agent" / "skills" / POINTER_SKILL_NAME
    if _is_owned_pointer_dir(legacy_dir) and apply_owned_edits(
        {legacy_dir / "SKILL.md": owned_pointer_edit},
        target_dir,
        label="Antigravity",
        prune=(legacy_dir, legacy_dir.parent, legacy_dir.parent.parent),
    ):
        print(f"  Removed legacy: .agent/skills/{POINTER_SKILL_NAME}/SKILL.md")


def _is_owned_pointer_dir(pointer_dir: Path) -> bool:
    """True for a real pointer directory that the Codex adapter does not own."""
    if pointer_dir.is_symlink() or not (pointer_dir / "SKILL.md").is_file():
        return False
    marker = pointer_dir / ADAPTED_MARKER
    return not marker.exists() and not marker.is_symlink()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_global(target_dir: Path) -> None:
    """Write the skill pointer to Antigravity's documented HOME-scoped skill
    dirs. ``~/.gemini/antigravity-cli/skills/`` is canonical for the CLI;
    ``~/.gemini/config/skills/`` is canonical for the IDE/shared product.
    Global rules reach Antigravity through ``~/.gemini/GEMINI.md``, which the
    Gemini generator owns, so no modular ``~/.gemini/config/rules/`` files are
    emitted here (rules stay project-local).
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    sync_workflow_skills(target_dir, (".gemini/config/skills", ".gemini/antigravity-cli/skills"))
    content = _pointer_skill_md()
    for rel in (".gemini/config/skills", ".gemini/antigravity-cli/skills"):
        skill_dir = target_dir / rel / POINTER_SKILL_NAME
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(content, encoding="utf-8")
        print(f"  Generated: {rel}/{POINTER_SKILL_NAME}/SKILL.md")


def _legacy_workflow(filename: str, render) -> str:
    notice = (
        "<!-- DEPRECATED: workflows retire 2026-11-01; use "
        f".agents/skills/{Path(filename).stem}/SKILL.md. "
        "https://antigravity.google/docs/migration/workflows-to-skills/ -->"
    )
    return render().replace("\n---\n", f"\n---\n\n{notice}\n", 1)


# Always-on rules, with the description Antigravity falls back to when the
# always-on budget is exceeded.
ALWAYS_ON_RULES = {
    f"{PREFIX}code-style.md": "Code style conventions for every language.",
    f"{PREFIX}testing.md": "Testing expectations for every change.",
    f"{PREFIX}security.md": "Security rules for code, secrets and input handling.",
    f"{PREFIX}workflow.md": "Development workflow, commits and quality gates.",
    f"{PREFIX}quality-standards.md": "ai-toolkit constitution and quality standards.",
    f"{PREFIX}output-mode.md": "Concise response style.",
}
AGENTS_INDEX_RULE = f"{PREFIX}agents-and-skills.md"
AGENTS_INDEX_DESCRIPTION = (
    "Index of ai-toolkit agent personas. Read it when a task matches a "
    "specialist role (security, database, frontend, debugging, and so on)."
)
LANG_COMMON_DESCRIPTION = (
    "Cross-language coding, testing, security and performance rules. Read "
    "before writing, reviewing or refactoring code."
)


def _agents_index() -> str:
    """Agent personas only: skills are discovered natively from
    ``.agents/skills/``, and the guideline sections duplicate the always-on
    quality-standards and workflow rules, so neither is repeated here."""
    return (
        "# AI Toolkit Agents\n\n"
        "Specialized agent personas. Apply their expertise for relevant tasks. "
        f"Skills are listed by the `{POINTER_SKILL_NAME}` skill.\n\n"
        f"{emit_agents_bullets()}\n"
    )


def _activated(filename: str, content_fn) -> callable:
    """Wrap a rule with the Antigravity trigger it needs to be loaded."""
    if filename in ALWAYS_ON_RULES:
        return partial(_render, content_fn, "always_on", ALWAYS_ON_RULES[filename])
    if rule_scope(filename) == CUSTOM_SCOPE:
        name = filename.removeprefix(CUSTOM_PREFIX).removesuffix(".md")
        return partial(_render, content_fn, "always_on", f"Registered rule {name}.")
    if rule_scope(filename) != LANG_SCOPE:
        return partial(_render, content_fn, "model_decision", AGENTS_INDEX_DESCRIPTION)
    lang = filename.removeprefix(LANG_PREFIX).removesuffix(".md")
    if lang in LANG_GLOBS:
        return partial(
            _render, content_fn, "glob", f"Coding rules for {lang} files.",
            LANG_GLOBS[lang],
        )
    description = (
        LANG_COMMON_DESCRIPTION if lang == "common"
        else f"Coding rules for {lang} code. Read before editing {lang} files."
    )
    return partial(_render, content_fn, "model_decision", description)


def _render(content_fn, trigger: str, description: str,
            globs: list[str] | None = None) -> str:
    return with_frontmatter(
        content_fn(), trigger=trigger, description=description, globs=globs,
        quoted=True,
    )


def _registered_rules(target_dir: Path, rules_dir: Path | None,
                      opt_in_rules: list[str] | None) -> dict[str, callable]:
    """Registered rules whose MCP servers Antigravity has configured."""
    metadata = load_sources(rules_dir) if rules_dir and rules_dir.is_dir() else {}
    return {
        f"{CUSTOM_PREFIX}{path.stem}.md": partial(rule_text, path, metadata.get(path.stem))
        for path in select_rule_files(
            rules_dir,
            clients=("antigravity",),
            project_dir=target_dir,
            opted_in=opt_in_rules or (),
        )
    }


def build_rules(target_dir: Path, *,
                language_modules: list[str] | None = None,
                rules_dir: Path | None = None,
                opt_in_rules: list[str] | None = None) -> dict[str, callable]:
    """Return ``.agents/rules/`` file names mapped to their rendered content."""
    rules = dict(STANDARD_RULES)
    rules[AGENTS_INDEX_RULE] = _agents_index
    rules.update(build_language_rules(language_modules))
    rules.update(_registered_rules(target_dir, rules_dir, opt_in_rules))
    return {name: _activated(name, content_fn) for name, content_fn in rules.items()}


def _warn_oversized(rules: dict[str, callable]) -> None:
    for name, content_fn in rules.items():
        size = len(content_fn().encode("utf-8"))
        if size > ANTIGRAVITY_RULE_LIMIT_BYTES:
            print(
                f"  WARNING: .agents/rules/{name} is {size} bytes; Antigravity "
                f"truncates rule files above {ANTIGRAVITY_RULE_LIMIT_BYTES} bytes"
            )


def generate(target_dir: Path, *,
             language_modules: list[str] | None = None,
             rules_dir: Path | None = None,
             emit_skill_pointer: bool = True,
             opt_in_rules: list[str] | None = None) -> None:
    """Write ``.agents/{rules,workflows}/`` and the skill pointer.

    ``emit_skill_pointer`` controls whether the pointer SKILL.md is written to
    ``.agents/skills/``. Set this option to ``False`` if you manage that
    directory yourself. ``opt_in_rules`` names opt-in registered rules this
    project asked for.
    """
    rules = build_rules(
        target_dir,
        language_modules=language_modules,
        rules_dir=rules_dir,
        opt_in_rules=opt_in_rules,
    )
    _warn_oversized(rules)
    # Native skills retain slash names after workflows retire on 2026-11-01.
    # Keep the legacy workflows and the existing skill-directory opt-out.
    if emit_skill_pointer:
        target_dir.mkdir(parents=True, exist_ok=True)
        sync_workflow_skills(target_dir, (".agents/skills",))
    write_rules(target_dir, rules, ".agents/rules")
    legacy = {name: partial(_legacy_workflow, name, render) for name, render in STANDARD_WORKFLOWS.items()}
    write_rules(target_dir, legacy, ".agents/workflows")
    if emit_skill_pointer:
        _write_skill_pointer(target_dir)


# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------

LOCAL_RULE_ROOTS = (".agents/rules", ".agents/workflows")
LOCAL_SKILL_ROOTS = (".agents/skills", ".agent/skills")
GLOBAL_SKILL_ROOTS = (".gemini/config/skills", ".gemini/antigravity-cli/skills")

def _is_managed_rule_name(name: str) -> bool:
    # Same ``ai-toolkit-*`` ownership rule ``write_rules`` uses to prune stale
    # files; these rule and workflow files carry no in-file marker.
    return name.endswith(".md") and rule_scope(name) is not None


def _remove(_content: bytes) -> None:
    return None


def _apply(target_dir: Path, global_install: bool, *, dry_run: bool) -> int:
    target = lexical_absolute(target_dir)
    if target.is_symlink() or not target.is_dir():
        raise RuntimeError(f"Unsafe Antigravity target directory: {target}")
    edits: dict[Path, OwnedEdit] = {}
    leaves: list[Path] = []
    if not global_install:
        for rel in LOCAL_RULE_ROOTS:
            root = target / rel
            for directory in (root.parent, root):
                if directory.is_symlink():
                    raise RuntimeError(
                        f"Refusing symlinked Antigravity rules directory: {directory}"
                    )
            leaves.append(root)
            if root.is_dir():
                edits.update({
                    path: _remove
                    for path in sorted(root.iterdir())
                    if _is_managed_rule_name(path.name)
                    and path.is_file() and not path.is_symlink()
                })
    for rel in GLOBAL_SKILL_ROOTS if global_install else LOCAL_SKILL_ROOTS:
        for path in workflow_skill_paths(target / rel):
            edits[path] = owned_workflow_skill_edit
            leaves.append(path.parent)
        pointer_dir = target / rel / POINTER_SKILL_NAME
        leaves.append(pointer_dir)
        # A symlinked pointer directory is skipped. One carrying a Codex
        # adapter marker belongs to the shared ``.agents/skills`` surface
        # that uninstall cleans separately.
        if _is_owned_pointer_dir(pointer_dir):
            edits[pointer_dir / "SKILL.md"] = owned_pointer_edit
    prune = {
        directory
        for leaf in leaves
        for directory in (leaf, *leaf.parents)
        if target in directory.parents
    }
    return apply_owned_edits(
        edits,
        target,
        label="Antigravity",
        prune=tuple(prune),
        dry_run=dry_run,
    )


def discover(target_dir: Path, *, global_install: bool = False) -> int:
    """Count managed Antigravity rules, workflows, and skill pointers.

    Local (``target_dir`` = project): ``.agents/rules/ai-toolkit-*.md``,
    ``.agents/workflows/ai-toolkit-*.md``, and the catalogue pointer in
    ``.agents/skills/`` and ``.agent/skills/``. Global (``target_dir`` =
    HOME): the pointer and owned workflow replacements in
    ``~/.gemini/config/skills/`` and ``~/.gemini/antigravity-cli/skills/``.
    """
    return _apply(target_dir, global_install, dry_run=True)


def cleanup(target_dir: Path, *, global_install: bool = False) -> int:
    """Remove what ``discover`` counts and return the number of files removed.

    Hooks and native agents have their own ``cleanup`` in
    ``generate_antigravity_hooks`` and ``generate_antigravity_agents``.
    """
    return _apply(target_dir, global_install, dry_run=False)


VALID_TRIGGERS = frozenset({"always_on", "model_decision", "glob", "manual"})


def diagnose_rules(project: Path, home: Path) -> list[str]:
    """Return rule files Antigravity would discard or truncate.

    A ``.agents/rules/*.md`` file without a valid ``trigger`` is silently
    discarded; any rule file above 24,000 bytes, including ``AGENTS.md``,
    ``GEMINI.md`` and the global ``~/.gemini/GEMINI.md``, is truncated.
    """
    problems: list[str] = []
    rules_dir = project / ".agents" / "rules"
    rule_files = sorted(rules_dir.glob("*.md")) if rules_dir.is_dir() else []
    for path in rule_files:
        try:
            trigger = parse_frontmatter(path.read_text(encoding="utf-8")).get("trigger")
        except (OSError, UnicodeDecodeError, FrontmatterError):
            trigger = None
        if trigger not in VALID_TRIGGERS:
            problems.append(
                f"{path}: no valid 'trigger:' frontmatter, so Antigravity discards it"
            )
    candidates = [project / "AGENTS.md", project / "GEMINI.md", *rule_files,
                  home / ".gemini" / "GEMINI.md"]
    for path in candidates:
        size = path.stat().st_size if path.is_file() else 0
        if size > ANTIGRAVITY_RULE_LIMIT_BYTES:
            problems.append(
                f"{path}: {size} bytes; Antigravity truncates rule files above "
                f"{ANTIGRAVITY_RULE_LIMIT_BYTES} bytes"
            )
    return problems


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    from paths import RULES_DIR
    generate(target, rules_dir=RULES_DIR)


if __name__ == "__main__":
    main()
