#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Lukasz Krzemien (biuro@softspark.eu)
# Source: https://github.com/softspark/ai-toolkit

"""Generate .cursorrules from app/agents/*.md and app/skills/*/SKILL.md.

Usage: ./scripts/generate_cursor_rules.py > .cursorrules
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generator_base import render_generator
from injection import strip_owned_sections
from secure_fs import OwnedEdit, apply_owned_edits, lexical_absolute

RULES_FILE = ".cursorrules"


def _edits(target_dir: Path) -> tuple[Path, dict[Path, OwnedEdit]]:
    target = lexical_absolute(target_dir)
    if target.is_symlink() or not target.is_dir():
        raise RuntimeError(f"Unsafe Cursor target directory: {target}")
    return target, {target / RULES_FILE: strip_owned_sections}


def discover(target_dir: Path) -> int:
    """Return 1 when ``.cursorrules`` holds ai-toolkit TOOLKIT sections."""
    target, edits = _edits(target_dir)
    return apply_owned_edits(edits, target, label="Cursor rules", dry_run=True)


def cleanup(target_dir: Path) -> int:
    """Strip ai-toolkit sections from ``.cursorrules``; delete it if nothing remains.

    Returns 1 when the file was rewritten or removed, else 0. A symlinked
    ``.cursorrules`` is skipped, never followed.
    """
    target, edits = _edits(target_dir)
    return apply_owned_edits(edits, target, label="Cursor rules")


if __name__ == "__main__":
    render_generator({
        "title": "# Cursor Rules — generated from ai-toolkit agents",
        "header_lines": [
            "# Auto-generated by scripts/generate-cursor-rules.sh — do not edit manually.",
            "# Regenerate: ./scripts/generate-cursor-rules.sh > .cursorrules",
        ],
        "intro_template": (
            "This repository uses the ai-toolkit — a shared AI development toolkit"
            " with specialized agent personas and skills."
        ),
        "agents_section": "## Available Agent Personas",
        "agents_intro": "Apply the expertise of these agents when working on relevant tasks:",
        "agents_format": "headings",
        "agents_level": "##",
        "skills_section": "## Available Skills",
        "skills_intro": "The following skills are available as slash commands or knowledge sources:",
        "skills_format": "headings",
        "skills_level": "##",
        "trailing_newline_after_skills": True,
        "guidelines": ["general"],
    })
