#!/usr/bin/env python3
"""Generate .opencode/plugins/ai-toolkit-hooks.js for opencode.

opencode plugins are JS/TS modules that receive a context with ``$`` (Bun
shell), ``project``, ``client``, ``directory``, ``worktree`` and return a
hooks object. Docs: https://opencode.ai/docs/plugins/

This generator emits a single-file plugin that bridges ai-toolkit's
shared Bash hooks (``~/.softspark/ai-toolkit/hooks/*.sh``) to opencode
lifecycle events. Mapping:

  opencode event              -> ai-toolkit Bash hook(s)
  ---------------------------------------------------------------
  session.created             -> session-start.sh + session-context.sh + mcp-health.sh
  tool.execute.before (Bash)  -> guard-destructive.sh + commit-quality.sh
  tool.execute.after          -> post-tool-use.sh
  message.updated             -> user-prompt-submit.sh + track-usage.sh
  session.deleted             -> session-end.sh + save-session.sh

Security: hooks are invoked via ``$`` with an argv array (no shell string
concatenation), so opencode event payloads cannot be coerced into shell
metacharacters. Non-zero exit codes are logged to stderr but never block
opencode (the toolkit's own Bash ``exit 2`` semantics are preserved for
PreToolUse guards — opencode receives the exit code via the return value).

Usage:
  python3 scripts/generate_opencode_plugin.py [target-dir]
"""
from __future__ import annotations

import sys
from pathlib import Path

PLUGIN_BODY = r"""// ai-toolkit opencode plugin — bridges shared Bash hooks to opencode events.
// Auto-generated by ai-toolkit. Do not edit by hand; re-run to update:
//   ai-toolkit opencode-plugin
// Docs: https://opencode.ai/docs/plugins/
//
// Hooks live at $HOME/.softspark/ai-toolkit/hooks/*.sh and are shared with
// Claude Code and Codex CLI. This plugin invokes them via Bun's `$` shell
// with an argv array — no string interpolation into the shell, so opencode
// event payloads cannot inject shell metacharacters.

const HOOKS_DIR = `${process.env.HOME}/.softspark/ai-toolkit/hooks`;

/** Invoke a Bash hook with a JSON payload on stdin. */
async function runHook($, script, payload) {
  const scriptPath = `${HOOKS_DIR}/${script}`;
  try {
    const input = JSON.stringify(payload ?? {});
    // `$` runs Bash; passing argv as an array avoids shell-metachar injection.
    const proc = $`bash ${scriptPath}`.env({
      ...process.env,
      AI_TOOLKIT_EVENT: payload?.event || "unknown",
    });
    proc.stdin.write(input);
    proc.stdin.end();
    const result = await proc.quiet().nothrow();
    if (result.exitCode !== 0 && result.exitCode !== 2) {
      // Exit 2 is the toolkit's "block" signal — pass through to opencode as a guard.
      process.stderr.write(
        `[ai-toolkit] ${script} exited ${result.exitCode}\n${result.stderr.toString()}`
      );
    }
    return result.exitCode;
  } catch (err) {
    process.stderr.write(`[ai-toolkit] failed to run ${script}: ${err.message}\n`);
    return 0;
  }
}

export const AiToolkitHooks = async ({ $, project, directory, worktree }) => ({
  event: async ({ event }) => {
    const payload = { event: event.type, project, directory, worktree };
    switch (event.type) {
      case "session.created":
        await runHook($, "session-start.sh", payload);
        await runHook($, "session-context.sh", payload);
        await runHook($, "mcp-health.sh", payload);
        break;
      case "session.deleted":
        await runHook($, "session-end.sh", payload);
        await runHook($, "save-session.sh", payload);
        break;
      case "message.updated":
      case "message.part.updated":
        await runHook($, "user-prompt-submit.sh", payload);
        await runHook($, "track-usage.sh", payload);
        break;
    }
  },

  "tool.execute.before": async (input, output) => {
    const payload = {
      event: "tool.execute.before",
      tool: input?.tool,
      args: output?.args,
      project,
    };
    if (input?.tool === "bash") {
      await runHook($, "guard-destructive.sh", payload);
      await runHook($, "commit-quality.sh", payload);
    }
  },

  "tool.execute.after": async (input, output) => {
    const payload = {
      event: "tool.execute.after",
      tool: input?.tool,
      result: output,
      project,
    };
    await runHook($, "post-tool-use.sh", payload);
  },
});

export default AiToolkitHooks;
"""


def generate(target_dir: Path) -> Path:
    """Write .opencode/plugins/ai-toolkit-hooks.js and return its path."""
    plugins_dir = target_dir / ".opencode" / "plugins"
    plugins_dir.mkdir(parents=True, exist_ok=True)
    path = plugins_dir / "ai-toolkit-hooks.js"
    path.write_text(PLUGIN_BODY, encoding="utf-8")
    return path


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    path = generate(target)
    rel = path.relative_to(target) if path.is_relative_to(target) else path
    print(f"Generated: {rel}")


if __name__ == "__main__":
    main()
