#!/usr/bin/env python3
"""Generate native Codex custom-agent TOML files."""

from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from emission import agents_dir
from frontmatter import frontmatter_field

AGENT_PREFIX = "ai-toolkit-"
MANAGED_MARKER = "# ai-toolkit-managed: codex-agent"


def _agent_body(agent_file: Path) -> str:
    text = agent_file.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    body = parts[2] if len(parts) == 3 else text
    return body.lstrip("\n").rstrip() + "\n"


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _render_agent(agent_file: Path) -> str:
    name = frontmatter_field(agent_file, "name")
    description = frontmatter_field(agent_file, "description")
    body = _agent_body(agent_file)
    return "\n".join(
        [
            "# Generated by ai-toolkit. Do not edit.",
            MANAGED_MARKER,
            f"name = {_toml_string(name)}",
            f"description = {_toml_string(description)}",
            f"developer_instructions = {_toml_string(body)}",
            "",
        ]
    )


def _is_managed(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        return False
    return MANAGED_MARKER in lines[:3]


def _unmanaged_agent_names(output_dir: Path) -> set[str]:
    names: set[str] = set()
    for path in sorted(output_dir.glob("*.toml")):
        if _is_managed(path):
            continue
        try:
            data = tomllib.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, tomllib.TOMLDecodeError):
            continue
        name = data.get("name")
        if isinstance(name, str) and name.strip():
            names.add(name)
    return names


def _cleanup_stale(output_dir: Path, expected: set[str]) -> int:
    removed = 0
    for output in sorted(output_dir.glob(f"{AGENT_PREFIX}*.toml")):
        if output.name in expected or not _is_managed(output):
            continue
        output.unlink()
        removed += 1
    return removed


def generate(target_dir: Path, config_root: Path | None = None) -> tuple[int, int]:
    base = config_root if config_root is not None else target_dir / ".codex"
    output_dir = base / "agents"
    output_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    expected: set[str] = set()
    unmanaged_names = _unmanaged_agent_names(output_dir)
    for agent_file in sorted(agents_dir.glob("*.md")):
        name = frontmatter_field(agent_file, "name")
        description = frontmatter_field(agent_file, "description")
        if not name or not description:
            continue
        if name in unmanaged_names:
            continue
        filename = f"{AGENT_PREFIX}{name}.toml"
        expected.add(filename)
        output = output_dir / filename
        if output.exists() and not _is_managed(output):
            continue
        output.write_text(_render_agent(agent_file), encoding="utf-8")
        written += 1
    return written, _cleanup_stale(output_dir, expected)


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    written, removed = generate(target)
    print(f"Generated: .codex/agents/ ({written} agents, {removed} stale removed)")


if __name__ == "__main__":
    main()
