#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Lukasz Krzemien (biuro@softspark.eu)
# Source: https://github.com/softspark/ai-toolkit

"""Generate Antigravity IDE ``.agents/rules/``, ``.agents/workflows/``, and
skill pointer files.

Antigravity 2.0 reads rules/workflows from the plural ``.agents/`` directory by
default; singular ``.agent/`` is still accepted as a backward-compatible
fallback (Antigravity checks plural first, then singular). We emit plural.
Antigravity reads rules from:
  * ``GEMINI.md`` (highest priority) — generated by ``generate_gemini.py``
  * ``AGENTS.md`` (cross-tool) — generated by ``generate_agents_md.py``
  * ``.agents/rules/*.md`` — per-category rule files (this generator)
  * ``.agents/workflows/*.md`` — workflow templates (this generator)

Antigravity also supports the Agent Skills standard. The canonical project
surface is ``.agents/skills/<skill-name>/SKILL.md``. The older singular
``.agent/skills/`` path remains a compatibility output only, so the skill
pointer is dual-emitted. We do not duplicate our full skill catalogue; instead we
emit a single pointer skill that teaches Antigravity to look up the real
catalogue in ``~/.softspark/ai-toolkit/app/skills/`` (global install) or
``.claude/skills/`` (local install).

Usage:
  python3 scripts/generate_antigravity.py [target-dir]

Writes rules/workflows to target-dir/.agents/{rules,workflows}/ and the skill
pointer to target-dir/.agents/skills/ (canonical) + target-dir/.agent/skills/
(legacy compatibility).
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from codex_skill_adapter import ADAPTED_MARKERS
from dir_rules_shared import (
    STANDARD_RULES,
    STANDARD_WORKFLOWS,
    build_language_rules,
    build_registered_rules,
    rule_scope,
    write_rules,
)
from emission import emit_skills_bullets
from secure_fs import OwnedEdit, apply_owned_edits, lexical_absolute
from skill_pointer import owned_pointer_edit


# ---------------------------------------------------------------------------
# Skill pointer — a single SKILL.md that directs Antigravity to our catalogue
# ---------------------------------------------------------------------------

POINTER_SKILL_NAME = "ai-toolkit-skill-catalogue"


def _pointer_skill_md() -> str:
    """Build the SKILL.md body for the pointer skill."""
    body = (
        "# AI Toolkit Skill Catalogue\n\n"
        "This workspace uses the ai-toolkit. Real skills are installed "
        "alongside Claude Code at `.claude/skills/` (project install) or "
        "`~/.claude/skills/` (global install). If the ai-toolkit installer "
        "has run, every skill below already exists as an agent-invocable "
        "SKILL.md on disk.\n\n"
        "## When to use this skill\n\n"
        "- You are asked to run a task that maps to one of the catalogued "
        "skills below.\n"
        "- You want to discover which skills the user has installed before "
        "reinventing the wheel.\n\n"
        "## How to invoke a catalogue entry\n\n"
        "1. Match the user's task to a skill name in the catalogue.\n"
        "2. Read the skill's SKILL.md from `.claude/skills/<name>/SKILL.md` "
        "or `~/.claude/skills/<name>/SKILL.md` (whichever exists).\n"
        "3. Follow its Rules, Gotchas, and When NOT to Use sections.\n\n"
        "## Catalogue (installed skills)\n\n"
        f"{emit_skills_bullets()}\n"
    )
    return (
        "---\n"
        f"name: {POINTER_SKILL_NAME}\n"
        "description: Index of ai-toolkit skills installed at .claude/skills/"
        " or ~/.claude/skills/. Read this first when the user's request "
        "matches a named skill.\n"
        "---\n"
        f"{body}"
    )


def _write_skill_pointer(target_dir: Path) -> None:
    """Write the pointer SKILL.md for both the IDE and the CLI surface.

    ``.agents/skills/`` is canonical. ``.agent/skills/`` is retained only for
    older Antigravity installations.
    """
    content = _pointer_skill_md()
    for tree in (".agents", ".agent"):
        skill_dir = target_dir / tree / "skills" / POINTER_SKILL_NAME
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(content, encoding="utf-8")
        print(f"  Generated: {tree}/skills/{POINTER_SKILL_NAME}/SKILL.md")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_global(target_dir: Path) -> None:
    """Write the skill pointer to Antigravity's documented HOME-scoped skill
    dirs. ``~/.gemini/antigravity-cli/skills/`` is canonical for the CLI;
    ``~/.gemini/config/skills/`` is canonical for the IDE/shared product.
    Antigravity RULES have no documented global file surface, so only the
    product-specific skill pointers are emitted globally (rules stay local).
    """
    content = _pointer_skill_md()
    for rel in (".gemini/config/skills", ".gemini/antigravity-cli/skills"):
        skill_dir = target_dir / rel / POINTER_SKILL_NAME
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(content, encoding="utf-8")
        print(f"  Generated: {rel}/{POINTER_SKILL_NAME}/SKILL.md")


def generate(target_dir: Path, *,
             language_modules: list[str] | None = None,
             rules_dir: Path | None = None,
             emit_skill_pointer: bool = True) -> None:
    """Write ``.agents/{rules,workflows}/`` and the dual skill pointers.

    ``emit_skill_pointer`` controls whether the pointer SKILL.md is written.
    ``.agents/skills/`` is the canonical workspace surface, while
    ``.agent/skills/`` is a legacy compatibility copy. Set this option to
    ``False`` if you manage those directories yourself.
    """
    rules = dict(STANDARD_RULES)
    rules.update(build_language_rules(language_modules))
    rules.update(build_registered_rules(rules_dir))
    write_rules(target_dir, rules, ".agents/rules")
    write_rules(target_dir, STANDARD_WORKFLOWS, ".agents/workflows")
    if emit_skill_pointer:
        _write_skill_pointer(target_dir)


# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------

LOCAL_RULE_ROOTS = (".agents/rules", ".agents/workflows")
LOCAL_SKILL_ROOTS = (".agents/skills", ".agent/skills")
GLOBAL_SKILL_ROOTS = (".gemini/config/skills", ".gemini/antigravity-cli/skills")

def _is_managed_rule_name(name: str) -> bool:
    # Same ``ai-toolkit-*`` ownership rule ``write_rules`` uses to prune stale
    # files; these rule and workflow files carry no in-file marker.
    return name.endswith(".md") and rule_scope(name) is not None


def _remove(_content: bytes) -> None:
    return None


def _apply(target_dir: Path, global_install: bool, *, dry_run: bool) -> int:
    target = lexical_absolute(target_dir)
    if target.is_symlink() or not target.is_dir():
        raise RuntimeError(f"Unsafe Antigravity target directory: {target}")
    edits: dict[Path, OwnedEdit] = {}
    leaves: list[Path] = []
    if not global_install:
        for rel in LOCAL_RULE_ROOTS:
            root = target / rel
            for directory in (root.parent, root):
                if directory.is_symlink():
                    raise RuntimeError(
                        f"Refusing symlinked Antigravity rules directory: {directory}"
                    )
            leaves.append(root)
            if root.is_dir():
                edits.update({
                    path: _remove
                    for path in sorted(root.iterdir())
                    if _is_managed_rule_name(path.name)
                    and path.is_file() and not path.is_symlink()
                })
    for rel in GLOBAL_SKILL_ROOTS if global_install else LOCAL_SKILL_ROOTS:
        pointer_dir = target / rel / POINTER_SKILL_NAME
        leaves.append(pointer_dir)
        # A symlinked pointer directory is skipped. One carrying a Codex (or
        # legacy DSH) adapter marker belongs to the shared ``.agents/skills`` surface
        # that uninstall cleans separately.
        if pointer_dir.is_symlink() or not (pointer_dir / "SKILL.md").is_file():
            continue
        if any(
            (pointer_dir / marker).exists() or (pointer_dir / marker).is_symlink()
            for marker in ADAPTED_MARKERS
        ):
            continue
        edits[pointer_dir / "SKILL.md"] = owned_pointer_edit
    prune = {
        directory
        for leaf in leaves
        for directory in (leaf, *leaf.parents)
        if target in directory.parents
    }
    return apply_owned_edits(
        edits,
        target,
        label="Antigravity",
        prune=tuple(prune),
        dry_run=dry_run,
    )


def discover(target_dir: Path, *, global_install: bool = False) -> int:
    """Count managed Antigravity rules, workflows, and skill pointers.

    Local (``target_dir`` = project): ``.agents/rules/ai-toolkit-*.md``,
    ``.agents/workflows/ai-toolkit-*.md``, and the catalogue pointer in
    ``.agents/skills/`` and ``.agent/skills/``. Global (``target_dir`` =
    HOME): the pointer in ``~/.gemini/config/skills/`` and
    ``~/.gemini/antigravity-cli/skills/``.
    """
    return _apply(target_dir, global_install, dry_run=True)


def cleanup(target_dir: Path, *, global_install: bool = False) -> int:
    """Remove what ``discover`` counts and return the number of files removed.

    Hooks and native agents have their own ``cleanup`` in
    ``generate_antigravity_hooks`` and ``generate_antigravity_agents``.
    """
    return _apply(target_dir, global_install, dry_run=False)


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    from paths import RULES_DIR
    generate(target, rules_dir=RULES_DIR)


if __name__ == "__main__":
    main()
